### ISSUE TITLE
Provide a Rust wrapper

### ISSUE THREAD

**Issue by lemire** [lemire/simdjson#100]
Rust is popular and a wrapper could be super efficient (no overhead).

**Comment by TkTech** [comment]
Looks like a squatter already grabbed the crate name with a fake package? Even has 11 downloads.

https://crates.io/crates/simdjson

**Comment by lemire** [comment]
@TkTech   Come on people! Thanks just not cool.

**Comment by TkTech** [comment]
I've started working on porting it this evening as a fun way to learn Rust. stage_one is complete for x86_64 and started experimenting on aarch64 (only available if using nightly) . Feature dispatch is surprisingly clean with `if_cfg` and feature macros.

It's unfortunate that it seems like to use `#[target_feature(enable ="avx2")]` requires that the entire function be marked unsafe. I'm hoping this limitation can be lifted in the future.

**Comment by SunDoge** [comment]
I made one but it's still in progress. [simdjson-rust](https://github.com/SunDoge/simdjson-rust)

**Comment by TkTech** [comment]
@SunDoge I noticed your project the other day but at the time it looked like you were porting it. Now it looks like you're binding the C++ lib. Are you doing two different versions or sticking with the wrapper?

**Comment by SunDoge** [comment]
@TkTech Hi. At first I wanted to port it as it is a great chance to learn simd. But I noticed this issue today and thought it easy to implement one. So I spent several hours on it. So yes, I'm doing two different versions. 

It seems that you are also working on the porting, would you like to join me or is there a repo that I can contribute to? I know little about simd and it's hard to do it myself.

**Comment by lemire** [comment]
I know a bit of Rust, so I might help a bit in either case.

**Comment by TkTech** [comment]
My port is only complete to stage 1, it's a way for me to learn rust so it's quite awful. I've been keeping the repo private (just shared with Lemire) to prevent anyone stumbling on it from Google and thinking it was usable. Probably better for effort to go into your port if you're familiar with rust, and it looks like you are.

One or the most annoying (but trivial) bits I've found with direct translation of simdjson is the signed/unsigned behavior. In rust all intrinsics use signed values, and in C++ all the intrinsics are unsigned. On the plus side rust's stricter checks have exposed a few likely bugs in the C++ stage1 where silent overflows can happen.

**Comment by lemire** [comment]
> On the plus side rust's stricter checks have exposed a few likely bugs in the C++ stage1 where silent overflows can happen.

Likely bugs? Please share.

**Comment by Licenser** [comment]
FWIW I’ve a almost working port of simdjson to rust (not a binding)

**Comment by lemire** [comment]
@Licenser That would be insanely great.

Note that a complete port does not remove the need for a wrapper. If you want to make perf. comparisons, a wrapper is great.

**Comment by Licenser** [comment]
ah sorry, I didn't mean to suggest that; those are complementary and I'd expect them to have different use cases :)

**Comment by lemire** [comment]
@Licenser  Don't apologize, I was merely setting the context.

**Comment by lemire** [comment]
Assigned to @ioioioio.

**Comment by lemire** [comment]
Ok. Let us close this given that @SunDoge's version is decent: https://github.com/SunDoge/simdjson-rust

**Comment by ofek** [comment]
I think this is its successor https://github.com/simd-lite/simd-json

**Comment by lemire** [comment]
@ofek You are linking to a port... not a wrapper... the link you offer does not use the C++ code...

**Comment by ofek** [comment]
Sorry I thought we were talking about a port, I saw that word mentioned a few times

**Comment by lemire** [comment]
@ofek Yes. I think that the two issues were mixed here...

We do have a wrapper, but I think @SunDoge would probably appreciate getting some help. :-)

The port has been going very well.

**Comment by Licenser** [comment]
We do have some catching up to do with all the great stuff that happened in simdjson 3 ;)
