### ISSUE TITLE
The single-header code should be a build artifact, not in the github repo

### ISSUE THREAD

**Issue by geofflangdale** [lemire/simdjson#106]
I'm not an expert in handling this, but the single-header version surely shouldn't be in the repo. It's just an artifact of the other code. It should appear when we build.

Otherwise it's going to be constantly getting changed and needing to be 'merged' as a result of people making unrelated changes elsewhere in the code base.

**Comment by lemire** [comment]
It is a convenience thing. If you are building a wrapper or something around the code, and you want to use the single-header code, then it is super easy if you can just pull the project and get the single-header version right there.

Building it is possible, of course, but right now this is done with a bash script (amalgamation.sh). This assumes bash a few other tools as a dependency. It won't work under Windows. It won't work as part of other build tools (pip, go, rust crate, swift package manager). 

Having it *in* the repo is not a requirement, of course, but not having to build it yourself is super nice.

**Comment by TkTech** [comment]
I believe he means a build artifact as in a CI build artifact. circleci/travis/appveyor can all save arbitrary files from the results of jobs, and can very easily push the results to github as a a release (looks exactly like uploading to pypi with twine). It's just as convenient since since for example on circleci I can get a URL that always points to the latest build artifact for the master branch.

**Comment by geofflangdale** [comment]
Nope, I actually meant in the git sense alone.

It just adds a bit of friction to any check-in, and I'm thinking it will be a real pain to merge multiple changes. But @lemire gives a good justification for why it's that way (the Windows and other build chains). So unless there's a wonderful way of dodging this problem.

However, I think TkTech's solution is the right one - our CI system could keep this up to date, no?

**Comment by lemire** [comment]
@geofflangdale I am not sure I grok the difference with what we do right now.

So, right now, the single-header code only gets changed manually. You have to call a makefile target (amalgamate) and then do a commit. If you don't type `make amalgamate`, the single-header code does not change.

I am trying to understand what you mean by...

> It just adds a bit of friction to any check-in (...)

Unless you do `make amalgamate`, these files should not change. If they do, then something is wrong and we should fix that.


The only benefit in scripting this through CI is that it one less thing to do when issuing releases. However, that's a tiny step in the process of issuing a release and, frankly, our releases are super easy to do right now.

**Comment by geofflangdale** [comment]
OK, I think I've been Doing It Wrong. I suppose I'm always nervous about having a single-header version that's not reflective of the latest code - just in case we have a performance blip or bug in the current code. So I always wind up updating the code via amalgamate, but I guess I should stop.

**Comment by lemire** [comment]
Speaking for myself, I have never run the benchmarks from the single-header version, but from the ``make`` code. It is possible, I suppose, that the single-header version could have different performance, but...

**Comment by geofflangdale** [comment]
I meant that I might fix (or break!) something performance-related in the
main version, then have someone clag the out-of-date single-header version
and raise an issue that seems confusing from the perspective of what I
would view the "current state of the code" to be.

It's really just a symptom of being in a 'not quite released state' and
will go away when this is more solid (thus my closing of this issue).
