### ISSUE TITLE
BMI / AVX2 Errors during compilation

### ISSUE THREAD

**Issue by Think7** [lemire/simdjson#115]
Greetings,

When including the header only version into my C++ project, I receive the following error messages:

```
../Common/simdjson/simdjson.h:91:2: warning: "BMI is missing?" [-W#warnings]
#warning "BMI is missing?"
 ^
../Common/simdjson/simdjson.h:35756:2: warning: "We require AVX2 support!" [-W#warnings]
#warning "We require AVX2 support!"
 ^
../Common/simdjson/simdjson.cpp:372:21: error: member access into incomplete type 'struct avx_processed_utf_bytes'
            previous.carried_continuations,
                    ^
../Common/simdjson/simdjson.cpp:366:38: note: forward declaration of 'avx_processed_utf_bytes'
                              struct avx_processed_utf_bytes &previous)
                                     ^
../Common/simdjson/simdjson.cpp:378:16: error: use of undeclared identifier 'avxcheckUTF8Bytes'
    previous = avxcheckUTF8Bytes(input_lo, &previous, &has_error);
               ^
../Common/simdjson/simdjson.cpp:379:16: error: use of undeclared identifier 'avxcheckUTF8Bytes'
    previous = avxcheckUTF8Bytes(input_hi, &previous, &has_error);
               ^
../Common/simdjson/simdjson.cpp:603:34: error: variable has incomplete type 'struct avx_processed_utf_bytes'
  struct avx_processed_utf_bytes previous {};
                                 ^
../Common/simdjson/simdjson.cpp:366:38: note: forward declaration of 'avx_processed_utf_bytes'
                              struct avx_processed_utf_bytes &previous) 
                                     ^
```

My hardware / compiler is as follows:

```
CPU: Intel Core i7-4980HQ
machdep.cpu.leaf7_features: SMEP ERMS RDWRFSGS TSC_THREAD_OFFSET BMI1 AVX2 BMI2 INVPCID FPU_CSDS
Compiler: Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.6.0
```

Thanks for your time and sharing this wonderful project!

**Comment by TkTech** [comment]
You're missing -march=native or -march=haswell. You haven't told gcc to actually use CPU-family specific features such as AVX2.

**Comment by lemire** [comment]
@TkTech is correct.

**Comment by lemire** [comment]
We require hardware support for AVX2 instructions. You have to make sure that you instruct your compiler to use these instructions as needed. Under compilers such as GNU GCC or LLVM clang, the flag -march=native used on a recent Intel compiler (Haswell or better) is sufficient. You may also use the flags -mavx2 -mbmi2. Under Visual Studio, you need to target x64 and add the flag /arch:AVX2.

**Comment by lemire** [comment]
I'm going to close this since I have updated the README with these instructions.

**Comment by Think7** [comment]
Thank you both for your help! I'm rather inexperienced with fiddly compiler switches.

Since my project is Qt based, i needed to add the following to my .pro file:

```
win32 {
    QMAKE_CXXFLAGS += /arch:AVX2
}

unix {
    QMAKE_CXXFLAGS += -march=native
}
```

Now i'm left with this one warning:

```
../Common/simdjson/simdjson.h:35731: warning: unused function 'avxcheckUTF8Bytes' 
[-Wunused-function]
```

**Comment by lemire** [comment]
That’s a harmless warning.

**Comment by TkTech** [comment]
@Think7 Just remember, if you intend for it to be compiled by the end user, use `-march=native`. If you intend to distribute it as a binary, choose `-march=haswell`. Using `native` tells the compiler to use all the available features of *your specific cpu*, which may have features processors even a few months older do not have. This tends to result in the most efficient binaries, but the least portable.

Using `-march=haswell` tells the compiler to instead target the Haswell family of processors which is the bare minimum for AVX2. These binaries may not be the most efficient, but they will be the most portable.

**Comment by lemire** [comment]
@Think7 

Would you be willing to contribute a small paragraph to explain to others how to use the library with Qt? It is best if people don't need to rediscover the wheel.
