### ISSUE TITLE
Project logo (professional grade)

### ISSUE THREAD

**Issue by lemire** [lemire/simdjson#117]
We need a project logo. 

I cannot draw.

**Comment by EgorBo** [comment]
Neither can I https://raw.githubusercontent.com/EgorBo/SimdJsonSharp/master/images/logo.png 🙂

**Comment by lemire** [comment]
Well, you win. I sure couldn't do better. :-) 

Let us go with that.

**Comment by EgorBo** [comment]
well, it's more like an idea for a designer 😄

**Comment by lemire** [comment]
@EgorBo  I get that but this is better than nothing.

**Comment by lemire** [comment]
Ok. So we now have Egor's logo as a starting point. It is clean and look good, but Egor is probably not a professional designer so let us assume that we can improve this logo. I am leaving the issue open.

**Comment by EgorBo** [comment]
@lemire yeah I am definitely not, but I've tried to improve it a bit and added an alpha: 
![ico](https://user-images.githubusercontent.com/523221/54229976-81282680-4516-11e9-8168-a1eeff50ddd7.png)

**Comment by lemire** [comment]
Maybe a new career is ahead of you!

Replacing the log with this... I think I will close this issue with this because your logo is quite nice. To my untrained eyes, this looks professional.
