### ISSUE TITLE
some bugs in  singleheader 

### ISSUE THREAD

**Issue by lihui** [lemire/simdjson#118]
singleheader/amalgamation_demo   report  well-formed  json as  not valid.
but when i  build  amalgamation_demo with  include files:
 #include "simdjson/jsonioutil.h"
#include "simdjson/jsonparser.h"
just as   tools/json2json

it works as i expected.

so i think there must be some bugs in  singleheader(snapshot and version@0.0.1)

**Comment by TkTech** [comment]
This is not enough information. Can you provide the JSON that failed to validate, or a minimum reproduction?

**Comment by lemire** [comment]
@lihui Tyler is correct. Can you share with us a JSON file where this issue arises.

**Comment by lemire** [comment]
I marked this as "unverified". We need to be able to reproduce this issue for us to work on it.

**Comment by lihui** [comment]
<pre><font color="#8AE234"><b>higgsli@higgsli-VirtualBox</b></font>:<font color="#729FCF"><b>~/work/demo/simdjson-0.0.1/singleheader</b></font>$ ../build/tools/amalgamation_demo  ../jsonexamples/twitter.json 
valid
<font color="#8AE234"><b>higgsli@higgsli-VirtualBox</b></font>:<font color="#729FCF"><b>~/work/demo/simdjson-0.0.1/singleheader</b></font>$ ./amalgamation_demo ../jsonexamples/twitter.json 
not valid
</pre>

**Comment by lihui** [comment]
<pre><font color="#8AE234"><b>higgsli@higgsli-VirtualBox</b></font>:<font color="#729FCF"><b>~/work/demo/simdjson-0.0.1/singleheader</b></font>$ cat amalgamation_demo.cpp 
/* auto-generated on Tue 26 Feb 2019 10:14:31 EST. Do not edit! */

#include &lt;iostream&gt;
#include &quot;simdjson.h&quot;
#include &quot;simdjson.cpp&quot;
int main(int argc, char *argv[]) {
  const char * filename = argv[1];
  std::string_view p = get_corpus(filename);
  ParsedJson pj = build_parsed_json(p); // do the parsing
  if( ! pj.isValid() ) {
    std::cout &lt;&lt; &quot;not valid&quot; &lt;&lt; std::endl;
  } else {
    std::cout &lt;&lt; &quot;valid&quot; &lt;&lt; std::endl;
  }
  return EXIT_SUCCESS;
}
</pre>

<pre><font color="#8AE234"><b>higgsli@higgsli-VirtualBox</b></font>:<font color="#729FCF"><b>~/work/demo/simdjson-0.0.1/tools</b></font>$ cat amalgamation_demo.cpp 
/* auto-generated on Tue 26 Feb 2019 10:14:31 EST. Do not edit! */

#include &lt;iostream&gt;
#include &quot;simdjson/jsonioutil.h&quot;
#include &quot;simdjson/jsonparser.h&quot;
int main(int argc, char *argv[]) {
  const char * filename = argv[1];
  std::string_view p = get_corpus(filename);
  ParsedJson pj = build_parsed_json(p); // do the parsing
  if( ! pj.isValid() ) {
    std::cout &lt;&lt; &quot;not valid&quot; &lt;&lt; std::endl;
  } else {
    std::cout &lt;&lt; &quot;valid&quot; &lt;&lt; std::endl;
  }
  return EXIT_SUCCESS;
}

</pre>

<pre><font color="#8AE234"><b>higgsli@higgsli-VirtualBox</b></font>:<font color="#729FCF"><b>~/work/demo/simdjson-0.0.1/tools</b></font>$ cat CMakeLists.txt 
add_cpp_tool(json2json)
add_cpp_tool(jsonstats)
add_cpp_tool(minify)
add_cpp_tool(amalgamation_demo)
</pre>

**Comment by lemire** [comment]
We welcome bug reports, but this is not nearly enough information for others to reproduce and/or identify your problems.

I am going to close this.

Please reopen if you can clearly explain your problem and provide complete steps and complete descriptions (with complete and precise sentences).
