### ISSUE TITLE
While- instead of if-statement in numberparsing.h

### ISSUE THREAD

**Issue by abolz** [lemire/simdjson#119]
This `while` https://github.com/lemire/simdjson/blob/afd9d729541d7a9c33f04a17239b2231988ff173/include/simdjson/numberparsing.h#L450-L455 in `parse_number` should be an `if` statement, since otherwise the following `if` statements will never be executed (and `expnumber` may overflow).

Or, assuming that the intent is to parse no more than 3 digits, it should be removed completely.

Aside: While parsing the significand, the signed integer `i` might overflow, too.

**Comment by lemire** [comment]
Thanks for your report.

We allow overflows and then catch them later by branching on the length of the number (it is faster than checking overflows on each operation given that most numbers will not overflow).

**Comment by lemire** [comment]
These while loop has no business being there. I simply removed it. Thanks for reporting the issue.

Closing.
