### ISSUE TITLE
jsonioutil::get_corpus Returns string_view to locally allocated buffer (leak)

### ISSUE THREAD

**Issue by Raincode** [lemire/simdjson#122]
```
std::string_view get_corpus(const std::string& filename) {
  std::FILE *fp = std::fopen(filename.c_str(), "rb");
  if (fp != nullptr) {
    std::fseek(fp, 0, SEEK_END);
    size_t len = std::ftell(fp);
    char * buf = allocate_padded_buffer(len);
    if(buf == nullptr) {
      std::fclose(fp);
      throw  std::runtime_error("could not allocate memory");
    }
    std::rewind(fp);
    size_t readb = std::fread(buf, 1, len, fp);
    std::fclose(fp);
    if(readb != len) {
      aligned_free(buf);
      throw  std::runtime_error("could not read the data");
    }
    return std::string_view(buf,len);
  }
  throw  std::runtime_error("could not load corpus");
}
```
Pardon me if I am wrong, but it looks like to me this function simply leaks `buf` by returning a std::string_view to a locally allocated buffer. std::string_view does not take ownership over that memory, so I would recommend returning a std::string instead. Repeated calls to get_corpus would eventually exhaust RAM. Or am I missing something here?

**Comment by lemire** [comment]
The documentation regarding this function is explicit that you are responsible for freeing the memory when you call this function...

```C++
// load a file in memory...
// get a corpus; pad out to cache line so we can always use SIMD
// throws exceptions in case of failure
// first element of the pair is a string (null terminated)
// whereas the second element is the length.
// caller is responsible to free (aligned_free((void*)result.data())))
// 
// throws an exception if the file cannot be opened, use try/catch
//      try {
//        p = get_corpus(filename);
//      } catch (const std::exception& e) { 
//        aligned_free((void*)p.data());
//        std::cout << "Could not load the file " << filename << std::endl;
//      }
std::string_view  get_corpus(const std::string& filename);
```

**Comment by lemire** [comment]
I am closing this. There is a leak if and only if the users do not follow the usage recommendations.

A ``std::string`` cannot be used because we require appropriate padding. This is covered by a previous issue https://github.com/lemire/simdjson/issues/32#issuecomment-466313473

**Comment by Raincode** [comment]
Ah I understand, my bad. Sorry for the inconvenience. I guess users can just implement their own tiny RAII wrapper then.

**Comment by lemire** [comment]
The library is still very young. We could improve this aspect without too much trouble. I closed your issue mostly because it is already covered by another issue. You could not know this because the previous issue was under a different (misleading?) title. I fixed that.
