### ISSUE TITLE
possible bug with the json `0`

### ISSUE THREAD

**Issue by Licenser** [lemire/simdjson#131]
I think if the json `0` is passed in, parse_number function will fail as when checking the (next) character (null-byte) is_not_structural_or_whitespace_or_exponent_or_decimal will return true.

**Comment by lemire** [comment]
You mean if the whole document is just 0?

**Comment by Licenser** [comment]
Yap! I'm sorry I don't have the c++ toolchain here right now to add a test :( but from what I read in the code it would:
go to the [number in base](https://github.com/lemire/simdjson/blob/ddc2867f944284a5ae46c69c4758040d6ff756a9/src/stage2_build_tape.cpp#L184) case then copy the "0" into `0` followed by `\0` and go off to `parse_number` and hit [the first case](https://github.com/lemire/simdjson/blob/master/include/simdjson/numberparsing.h#L370) move the pointer one forward to the `\0` then call `is_not_structural_or_whitespace_or_exponent_or_decimal` which on `0` reutrns `true` and [fail parse_number](https://github.com/lemire/simdjson/blob/master/include/simdjson/numberparsing.h#L376).

**Comment by Licenser** [comment]
To be clear I the parsed (failing) document would be the character '0'  not a null byte.

**Comment by lemire** [comment]
@Licenser That's fine. I just wanted to clarify the bug report. I now understand it, I think.

Thanks.

**Comment by lemire** [comment]
I'm going to intentionally delay fixing this because @geofflangdale is doing so engineering that might conflict with such a fix.

**Comment by Licenser** [comment]
I have no hurry with it :), just wanted to report it before I forgot

**Comment by lemire** [comment]
Fixed and verified in a branch about to be merged.
