### ISSUE TITLE
Question on use of _mm256_shuffle_epi8

### ISSUE THREAD

**Issue by quinnj** [lemire/simdjson#133]
First of all, huge thanks and kudos for an awesome repo + white paper going into details. This is a technique I've been interested in since hearing about the Mison paper and I've had a ton of fun diving into your code here.

In your paper (https://arxiv.org/pdf/1902.08318.pdf), you mention:
> Mison does one SIMD comparison per character (‘:’, ‘\’, ‘:’, ‘"’, ‘{’, ‘}’). We proceed similarly to identify the quotes and the backslash characters.

Just wondering why you decided to do individual comparisons for the `\` and `"` characters, as opposed to including them as a another (or two separate) vector categorizations when doing the `_mm256_shuffle_epi8` later? I'm wondering if it's related to the cost of doing `_mm256_shuffle_epi8`?

**Comment by lemire** [comment]
The shuffle instruction is itself dirt cheap... The question is good though... We could do it differently... but there would not be any benefit since we need a mask for each of these characters.

Leaving open since we need to answer this well.

**Comment by lemire** [comment]
Version 3 of the paper (https://arxiv.org/abs/1902.08318v3) solves this issue: we document the performance differential, see appendix B.

Closing. Reopen if the revised manuscript does not answer your question.
