### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by michaeleisel** [lemire/simdjson#144]
I want to build this library for an iOS app. Ordinarily I would use `./configure --host=aarch64-apple-ios --target=aarch64-apple-ios` to configure things running `make`, but in this case there doesn't appear to be a configure script. What should I do?

**Comment by lemire** [comment]
There is a single-header version that should work for you, so no need for complicated instructions.

However, the ARM port is still in progress once we are happy with it, we will have to provide instructions... but they will be simple enough. A Swift wrapper would be easy.

cc @geofflangdale

**Comment by michaeleisel** [comment]
Nice, i've written a library that replaces `JSONSerialization` (the swift library for turning json into the basic swift data structures like dictionaries) and plan to replace `Codable` and `Decodable` (the swift library for turning json into objects). its built on top of RapidJSON currently, but i'll replace it with simdjson when it's ready

**Comment by michaeleisel** [comment]
by codable and decodable i just mean, JSONEncoder and JSONDecoder

**Comment by ppamorim** [comment]
@michaeleisel Please share it with us. :)

**Comment by lemire** [comment]
Note that we have ARM NEON support working now in a branch (passing all tests) so it should be possible, soon, to deploy on Apple's ARM processors... and thus ios. Producing a Swift wrapper and support SwiftPM should be relatively easy.

**Comment by ppamorim** [comment]
@lemire Any plans to migrate to Android (specially Kotlin)?

**Comment by lemire** [comment]
@ppamorim Android won't be a problem... Kotlin might be.

**Comment by ppamorim** [comment]
Well, Kotlin supports C++ like Java does when compiling for JVM. Would you recommend to create an Java base version and a Kotlin version afterwards or create a specific version for each version? Mind that Kotlin compiles to native too, so I think the second alternative is better.

**Comment by lemire** [comment]
@ppamorim I realize that if you have Java wrappers, then kotlin is easy... but that's an open issue right now...
https://github.com/lemire/simdjson/issues/121

I am not personally very familiar with Kotlin (beyond the syntax). Would you be willing to help at least document the issue of Kotlin/simdjson? We can create a new issue and discuss it there.

**Comment by ppamorim** [comment]
@lemire Yes that's perfect. But let's wait the merge of the ARM NEON support and implement the basics of the Swift version so I can use it as base for the Java/Kotlin implementation.

**Comment by lemire** [comment]
We do have NEON now, and it works under ios.

**Comment by lemire** [comment]
@michaeleisel 

Here is an app demo that runs under ios...

https://github.com/lemire/iossimdjson


Here is a blog post about the results...
https://lemire.me/blog/2019/07/10/parsing-json-using-simd-instructions-on-the-apple-a12-processor/

**Comment by michaeleisel** [comment]
Very nice! I will say that the phones that can use the most modern instructions are also the ones least in need of performance improvements. The big targets are the slowest phones that still have decent market reach. My finger isn’t quite on the pulse these days but I’d imagine it’s the iPhone 7 and 8. Of course, year over year things change quickly, and A12 phones will soon be “slow”. And it will still be a big win for them. FYI I once made a 6x faster parser vs. RapidJson that works on iPhone 7 using vectorization, I can share the code if you’d like. Also FYI, development has stalled a bit on my own Swift wrappers and it’s not polished for me to want to release, hence the delay.

**Comment by michaeleisel** [comment]
To be clear, I don’t know what instructions are being used, I just assumed they include some of the more recent vector instructions

**Comment by lemire** [comment]
@michaeleisel We use 64-bit ARM (aarch64). It is commonplace if not universal at this point. It should run fine on the iPhone 7 and even much older phones.

Performance is another matter. There is really little sense in running something like simdjson on old hardware. The point of simdjson is to show that we can make better use of the power of modern chips via SIMD instructions, superscalarity and so forth.

If you have a narrow processor with slow SIMD instructions, simdjson may even be slower than traditional methods. It is designed to run fast on modern, wide processors with fast SIMD.

Generally speaking, old software is fine for old hardware. What harms old hardware is often new software designed for new hardware.

What we are doing with simdjson is build new software for the current best hardware, as well as the  upcoming hardware. Accelerating processing on old hardware is not a goal.

This is even more true, I would think, on mobile hardware... given that the half life of a modern phone is something like 3 years... and older devices survive as "hands me down" for non-critical tasks (like games for kids). What we want to know about is the performance on the next iPhone... really...

**Comment by ppamorim** [comment]
I am working in a wrapper in objc compatible with Swift :D

**Comment by lemire** [comment]
@michaeleisel Just to contradict myself, I am getting great results on a weak ARM core...

Parsing JSON quickly on tiny chips (ARM Cortex-A72 edition)
https://lemire.me/blog/2019/07/11/parsing-json-quickly-on-tiny-chips-arm-cortex-a72-edition/

**Comment by michaeleisel** [comment]
Yeah that aligns with what I’ve seen

**Comment by luizperes** [comment]
This is a very big step! Good job, everyone!

**Comment by lemire** [comment]
Given that me and others have produced ios apps, I'm going to close this issue.

**Comment by michaeleisel** [comment]
"or a 64-bit ARM processor (ARMv8-A): this covers a wide range of mobile processors, including all Apple processors currently available for sale."

to be clear, does it support the iPhone 5s and up?

**Comment by lemire** [comment]
@michaeleisel Yes. [The iPhone 5s has a 64-bit processor](https://en.wikipedia.org/wiki/Apple_A7).

**Comment by michaeleisel** [comment]
I've released a swift library built on simdjson. It's a drop-in replacement of JSONDecoder, and it's 4-5x times the speed of Apple's: https://github.com/michaeleisel/zippyjson

Here were some takeaways:
- I had to store many ParsedJson::iterators, so the copy constructor had to be fast. I got rid of the depthindex array and just stored the depth (I didn't need `up()`)
-  I tried to support SwiftPM, but there was one blocking issue: https://forums.swift.org/t/modify-vector-extensions/27999 . Also note that SwiftPM only supports MacOS and has a lot of unexpected issues that Cocoapods and Carthage do not
- I used `strtod` for perfect float parsing while that is figured out, with an opt-in to use the existing simdjson float parsing
- For each dictionary that keys are being looked up upon, I store an iterator. The iterator sits at the last key that was looked up. If the keys are looked up in the order that they exist in the JSON, the lookups are very fast. If the iterator searches to the end, it loops back around from the beginning to find a key. The weird one was when the dictionary is empty. In that case, I used a dictionary with one dummy k-v pair (`{"":""}`).
- I think I found a bug in `prev`, where it goes back the same amount every time, even when the previous data type is of a variable size
- I checked the whole json at the start to see if there were any non-ASCII keys, in which case I let Apple's version do the parsing

**Comment by lemire** [comment]
@michaeleisel Fantastic. I have reshared the link and add a link from simdjson.

> Also note that SwiftPM only supports MacOS

Surely Linux is supported as well. Maybe you mean that you can't support ios with SwiftPM?

> I used strtod for perfect float parsing while that is figured out, with an opt-in to use the existing simdjson float parsing

Great.

> I checked the whole json at the start to see if there were any non-ASCII keys, in which case I let Apple's version do the parsing

That seems drastic?

**Comment by michaeleisel** [comment]
> Surely Linux is supported as well. Maybe you mean that you can't support ios with SwiftPM?

Correct, that's what I meant

> That seems drastic?

What alternative would you suggest? I could do that check during parsing, which I could see being faster, but otherwise I don't know. In any case, it's only about ~3% of the total time.

FYI simdjson functions, including the initial parsing, only take up like 25% of the total time or less, the rest is spent in Swift

**Comment by lemire** [comment]
> What alternative would you suggest?  

Can you elaborate on why you can't always use simdjson? What is wrong with non-ASCII keys?

**Comment by michaeleisel** [comment]
Right now it uses `memcmp`/`strcmp` for key comparison, which doesn't work for non-ASCII because different `char *`s can represent the same UTF-8 string (canonical vs. non-canonical representations). So then you have to convert everything to canonical, and you can't just do it in-place since the canonical representation may take more space. So it's a hassle that I just didn't want to deal with.

**Comment by lemire** [comment]
@michaeleisel 

Good point, but I thought that Swift was already using UTF-8 natively, right? So if you have two UTF-8 char*, Swift ought to be able to compare them for us, no?

What I understand is that you are relying on simdjson for the string comparison, and we don't support Unicode equivalence.

**Comment by michaeleisel** [comment]
If you were to put everything into Swift strings, that would be a simple way to do it. However, that sort of thing often comes at a substantial performance cost. Generally the way I do Swift/ObjC APIs is, get the Swift/ObjC inputs and immediately convert to C-level data types, do all the work, then at the very last bit convert back to Swift/ObjC data types. See https://github.com/michaeleisel/zippyjson#why-is-it-so-much-faster

**Comment by lemire** [comment]
@michaeleisel I am not arguing that you should do things differently.

Have you found JSON files where keys are *not* ASCII?

**Comment by michaeleisel** [comment]
No, and I hope I never do, but in the spirit of being a drop-in replacement for JSONDecoder I want to provide a similar level of support for devs as Apple does, and Apple supports this.

**Comment by michaeleisel** [comment]
So I understand whichever way simdjson goes with this, I just know that I'll continue to support it

**Comment by lemire** [comment]
@michaeleisel I am just wondering how simdjson might better support this issue.

I think that's a good start...
https://github.com/lemire/simdjson/issues/264

**Comment by michaeleisel** [comment]
To go to another point, and I don't know what the current thoughts are on the architecture, but what would've been nicest for me is where the iterator keeps a pointer to the top of the array/dictionary and then keeps its own private iterator that keeps track of the last place it traversed to. Then you can performantly search for keys in sequence and not have to think about that state (and the case where it's empty) as a consumer. This would make the API on par, for my usage at least, with rapidjson's.

**Comment by lemire** [comment]
@michaeleisel If you have a proposal, can you turn it into a distinct issue? Otherwise it is hard to keep track of the ideas...

**Comment by lemire** [comment]
@michaeleisel For example, we have `move_to_key` function which may do what you want... But in any case, it is probably best to open a new issue if you have ideas to discuss.

**Comment by kobi-ca** [comment]
hows the ARM port as of today end April 2020 ?

**Comment by lemire** [comment]
> hows the ARM port as of today end April 2020 ?

There is no ARM port. The simdjson library supports ARM. If you have a 64-bit ARM system, simdjson should run on it. We have CI tests in place.

We do not support 32-bit systems (either ARM or x86).

**Comment by kobi-ca** [comment]
> > hows the ARM port as of today end April 2020 ?
> 
> There is no ARM port. The simdjson library supports ARM. If you have a 64-bit ARM system, simdjson should run on it. We have CI tests in place.
> 
> We do not support 32-bit systems (either ARM or x86).

perfect! many thanks @lemire
