### ISSUE TITLE
Bug in the copy constructor of iterator

### ISSUE THREAD

**Issue by Skyprophet** [lemire/simdjson#145]
https://github.com/lemire/simdjson/blob/49332d3e907971a1927468ecc4a76673b0d718c8/src/parsedjsoniterator.cpp#L37

This line should be:

    memcpy(depthindex, o.depthindex, pj.depthcapacity * sizeof(depthindex[0])); 

Or it is violating `o` being constant. Semantically, I believe the copy target should be the newly constructed iterator.

**Comment by lemire** [comment]
You are, of course, correct.

**Comment by Skyprophet** [comment]
Should I submit a PR or it is easier to just fix it on your side?

**Comment by lemire** [comment]
The benefit of a PR is that you get credit for the fix in the logs. A PR is invited.

However, if you do not issue a PR, we will fix the bug otherwise.
