### ISSUE TITLE
Benchmark with dbSNP

### ISSUE THREAD

**Issue by lemire** [lemire/simdjson#147]
NIH makes available large (very large) JSON files.

ftp://ftp.ncbi.nih.gov/snp/latest_release/JSON/JSON_README.txt

These files span several gigabytes and may therefore require some care.

**Comment by lemire** [comment]
These files, though labelled as "JSON" are actually lists of JSON entries.

**Comment by lemire** [comment]
See https://github.com/lemire/simdjson/issues/188

**Comment by piotte13** [comment]
You can assign to me this issue as well as #188. 
Let's make it happen!
