### ISSUE TITLE
SEGFAULT in parse_string

### ISSUE THREAD

**Issue by technateNG** [lemire/simdjson#148]
There is a bug in parse_string function which results segfault. 
You can trigger error by providing input which contains non closed quotes.
For example:
- "[
- {"1": 1, ":2}

Bug exists because if you don't have closing quote inside 32 byte range, function adds additional 32 bytes without checking length of input string. When you don't provide closing quote in whole input, function loops to segment bounds causing segfault.

**Comment by lemire** [comment]
This sounds credible. I see you have a PR already!
