### ISSUE TITLE
Heap Corruption error on several inputs

### ISSUE THREAD

**Issue by Anders-E** [lemire/simdjson#150]
While experimenting with fuzzing, me and @EmilGedda discovered a bunch of inputs to simdjson that result in heap corruption errors.

Here's an archive of inputs discovered complete with the gcc AddressSanitizer logs for each crash: [simdjson_heap_corruption.zip](https://github.com/lemire/simdjson/files/3131968/simdjson_heap_corruption.zip)

We've also ran many of these inputs through `amalgamation_demo.cpp` located in the `singleheader` directory and can confirm that these do indeed cause either crashes due to heap corruption or strange behavior. This includes erroneous validation of the input (labelling invalid JSON as valid and vice versa) as well as just silent crashes.

**Comment by lemire** [comment]
Great stuff! Thank you!

We shall fix those in an upcoming release. 

Later this summer, we shall have systematic and thorough fuzz testing in place.

**Comment by Anders-E** [comment]
Glad to hear it! I hope some of this data can be of help to you.

**Comment by lemire** [comment]
> I hope some of this data can be of help to you.

Yes. I believe so.

**Comment by lemire** [comment]
Fix is in: https://github.com/lemire/simdjson/commit/f75280ac9c892406e6354ef516f7c9765d10f5ab

Your examples were helpful. They allow me to identify two real problems. It is likely that there were more, but I did some more fixing earlier.

We now test systematically over your examples.

**Comment by Anders-E** [comment]
Great to hear!
