### ISSUE TITLE
Acccess Violation with reproducible test case based on std::string

### ISSUE THREAD

**Issue by Skyprophet** [lemire/simdjson#154]
Build environment:
- Windows 10 1803
- Visual Studio Community 2019 16.0.3
- CMake 3.14.2
- Intel Core i7 7700K, 64GB RAM

Problematic code:

    #include <cassert>
    #include <vector>
    #include <string>

    #include "simdjson/jsonparser.h"

    int main(int argc, char *argv[]) {
      const size_t n_records = 1000000;
      std::vector<std::string> data;
      char buf[1024];
      for (size_t i = 0; i < n_records; ++i) {
        auto n = sprintf(buf, "{\"id\": %zu, \"name\": \"name%zu\", \"gender\": \"%s\", \"school\": {\"id\": %zu, \"name\": \"school%zu\"}}",
          i, i, (i % 2) ? "male" : "female", i % 10, i % 10);
        data.emplace_back(std::string(buf, n));
      }

      ParsedJson pj;
      pj.allocateCapacity(1LL << 25);
      for (auto& rec : data) {
        auto ok = json_parse(rec.c_str(), rec.length(), pj);
        if (ok != 0 || !pj.isValid()) {
          printf("Something is wrong!!!\n");
        }
      }
    }

Debug Output:

![image](https://user-images.githubusercontent.com/768038/57351693-16632800-7120-11e9-9198-fe0c861b3bf2.png)

Note that the following code will run without any exceptions:

    #include <cassert>
    #include <vector>
    #include <string>

    #include "simdjson/jsonparser.h"

    int main(int argc, char *argv[]) {
      const size_t n_records = 1000000;
      char buf[1024];
      ParsedJson pj;
      pj.allocateCapacity(1LL << 25);
      for (size_t i = 0; i < n_records; ++i) {
        auto n = sprintf(buf, "{\"id\": %zu, \"name\": \"name%zu\", \"gender\": \"%s\", \"school\": {\"id\": %zu, \"name\": \"school%zu\"}}",
          i, i, (i % 2) ? "male" : "female", i % 10, i % 10);
        auto ok = json_parse(buf, n, pj);
        if (ok != 0 || !pj.isValid()) {
          printf("Something is wrong!!!\n");
        }
      }
    }

I suspect it is a memory boundary violation when SIMD instructions trying to access the memory outside the buffer reserved in `std::string`. A potential solution is padding.

Also, an interesting thing I found is that the same code will work without problem with Linux (Fedora 30, GCC 9.0.1).

**Comment by lemire** [comment]
Ah. Ah. Something appears fishy. I think that this might be a genuine bug.

**Comment by lemire** [comment]
Note: I do not expect that this is related to Windows at all. I will retitle accordingly.

**Comment by lemire** [comment]
Flagging as a bug.

**Comment by lemire** [comment]
Your test is now part of our unit tests. Should be fine. Reopen if the problem persist.

(Note that I have not yet issued a release or updated the single-header version. If you need that, let me know.)

**Comment by lemire** [comment]
I have issued a new release. Please test it out.
