### ISSUE TITLE
Inline some of the stage2 FSM

### ISSUE THREAD

**Issue by Licenser** [lemire/simdjson#158]
While implementing the stage2 FSM logic in rust I found that inlining some stages via macros worked well and improved the performance.

Rust has no goto so it probably has a bit more effect there but it might also save come jump instructions in c++.

I did inline the following stages:
* object_begin
* object_continue
* array_begin
* array_continue

Would it be worth investigating the same approach in c++

**Comment by lemire** [comment]
Can you elaborate on what you mean by 'inlining'?

**Comment by Licenser** [comment]
Ah yes sure!

I created macros for the states listed, and instead of jumping to the state (or in rust case continuing the state loop) the macro gets called inlining the state where it the jump would otherwise happen.


I'm seeing if I can put together a simple example for array continue (as it's the simplest of the lot).

**Comment by Licenser** [comment]
reading again over the c-fsm it seems to make less sense you're using break which doesn't do a jump in most cases. I should have checked that before, the only time the macro approach would prevent change the code is in the scope-end cases so it's probably not worth it. I'll close that, sorry for the un-needed ticket.

**Comment by Licenser** [comment]
To add context even so it doesn't make much differnce this is the change I was thinking about: https://github.com/Licenser/simdjson/commit/5588fa491f52602e84b37dfa1a2bf668bd07149d

**Comment by lemire** [comment]
It does not sound silly at all to me. I don't know about the exact thing you were thinking about, but it seems that there are certainly scenarios where we could fatten our code to avoid jumps. That's the idea, right?



cc @geofflangdale
