### ISSUE TITLE
MSVC portability: Warning level 3, possible loss of data.

### ISSUE THREAD

**Issue by Skyprophet** [lemire/simdjson#160]
In `portability.h` line 22 and line 26.

    static inline int trailingzeroes(uint64_t input_num) {
        return _tzcnt_u64(input_num);
    }
    
    static inline int leadingzeroes(uint64_t  input_num) {
        return _lzcnt_u64(input_num);
    }

When compiling with MSVC warning level 3, it will report conversion from `__int64` to `int`, possible loss of data.

I would suggest to add an explicit `static_cast` to avoid that.

**Comment by lemire** [comment]
Can you propose a PR?

Note: these functions generate a number between 0 and 64 so the "loss" of data warning is almost surely bogus.

**Comment by Skyprophet** [comment]
Doing it now.

**Comment by lemire** [comment]
Well, I am fond of explicit casts.

**Comment by lemire** [comment]
Closing thanks to your PR.
