### ISSUE TITLE
CMake Policy Conflict

### ISSUE THREAD

**Issue by Skyprophet** [lemire/simdjson#164]
In the new `CMakeLists.txt`, CMP0069 is enabled which follows the cmake policy after version 3.9. However, in `FindCPack.cmake`, all the target will be pull down to cmake policy version 3.0.0.

When use `simdjson` in a subproject, it will pop up tons of warning like below:

    CMake Warning (dev) at third_party/simdjson/tools/cmake/FindCTargets.cmake:7 (add_executable):
      Policy CMP0069 is not set: INTERPROCEDURAL_OPTIMIZATION is enforced when
      enabled.  Run "cmake --help-policy CMP0069" for policy details.  Use the
      cmake_policy command to set the policy and suppress this warning.

      INTERPROCEDURAL_OPTIMIZATION property will be ignored for target
      'jsoncheck'.
    Call Stack (most recent call first):
      third_party/simdjson/tests/CMakeLists.txt:8 (add_cpp_test)
    This warning is for project developers.  Use -Wno-dev to suppress it.

Remove the following code in `tools/cmake/FindCTargets.cmake` will solve the problem:

    if (CMAKE_VERSION VERSION_GREATER 3.0.0)
        cmake_policy(VERSION 3.0.0)
    endif ()

**Comment by lemire** [comment]
Want to issue a  PR? (This way you get credit for the fix.)

**Comment by lemire** [comment]
Closing.
