### ISSUE TITLE
Add a pointer based interface to facilitate field access.

### ISSUE THREAD

**Issue by Skyprophet** [lemire/simdjson#175]
Right now, simdjson only supports an iterator based interface to navigate through parsed document. It would be nice to have an interface that supports pointer like interface.

An example is from [Rapidjson](http://rapidjson.org/md_doc_pointer.html).

Personally, I think it is more natural to have the query look like:
- `a.b.c`
- `a[0].c`
- `b.*.a`
- `b[*].c`

I would argue having such an interface will significantly boost the usability of simdjson.

**Comment by lemire** [comment]
> I would argue having such an interface will significantly boost the usability of simdjson.

I agree.

We will need help to make progress on this front.

**Comment by lemire** [comment]
Marked as help wanted.

**Comment by lemire** [comment]
JSON Pointer support has been added by @ioioioio , [following RFC6901](https://tools.ietf.org/html/rfc6901).

Reopen if it is does not resolve the issue to your satisfaction.
