### ISSUE TITLE
Parsed double values can contain error in last bits

### ISSUE THREAD

**Issue by plokhotnyuk** [lemire/simdjson#179]
As example 7e23 (0x44e287626ee52197 in raw binary representation) parsed as 6.999999999999999E23 (0x44e287626ee52198 in raw binary representation). 

Can it be documented if no other option to parse precisely?

**Comment by lemire** [comment]
Have you looked at this issue?

https://github.com/lemire/simdjson/issues/71

What you report is a real issue, but I think it is a duplicate.
