### ISSUE TITLE
Bug in number parsing

### ISSUE THREAD

**Issue by ioioioio** [lemire/simdjson#182]
Simdjson crashes when the number of digits after the dot minus the exponent is lower than -308.

Exemples:
1.0e-308
0.1e-308
0.01e-307

**Comment by lemire** [comment]
@ioioioio 

Thank you.

**Comment by lemire** [comment]
Verified. The bug is real.

**Comment by lemire** [comment]
Fixed in https://github.com/lemire/simdjson/pull/183

**Comment by lemire** [comment]
Closing.
