### ISSUE TITLE
Crash parsing numbers with e0, 19 digits and no dot.

### ISSUE THREAD

**Issue by ioioioio** [lemire/simdjson#187]
Simdjson crashes when the exponent is 0, the number of digits is higher or equal to 19, and there is no dot.
Examples:
1000000000000000000e0
1000000000000000000e-0
Interestingly, the current single header version only gave a TAPE_ERROR.

However, these do not crash and give the correct results:
1000000000000000000.0e0
1000000000000000000e10

Rapidjson correctly gives 1e+18 for 1000000000000000000e0. I've noticed Rapidjson parses numbers such 1e0 as floats, while Simdjson parses them as integers.

**Comment by lemire** [comment]
Thank you!

**Comment by lemire** [comment]
Fixed with recent commit.

Please keep finding new bugs.
