### ISSUE TITLE
Undetected error for null character in middle of number.

### ISSUE THREAD

**Issue by ioioioio** [lemire/simdjson#193]
simdjson fails to detect an error when a null character is in the middle of a number.

Example:
char json[] = "111";
json[1] = 0;

**Comment by lemire** [comment]
Thank you.

**Comment by ioioioio** [comment]
well... actually it is also undetected at the end of a number.

**Comment by lemire** [comment]
Issue fixed. Please retest and validate. Reopen if the issue remains.
