### ISSUE TITLE
Port to ARM Neon

### ISSUE THREAD

**Issue by lemire** [lemire/simdjson#20]
... eventually...

**Comment by geofflangdale** [comment]
Anyone curious about this should note that I'm working on this at the moment. Suggestions welcome. I estimate something working in trunk by the end of March 2019.

**Comment by lemire** [comment]
+1

**Comment by lemire** [comment]
> I estimate something working in trunk by the end of March 2019.

Now, that's a real programmer. (Today is March 29.)

**Comment by geofflangdale** [comment]
There is code to do a preliminary version of ARM NEON. It does not yet have a proper build setup - to build, you will need to put `-march=armv8.2-a+crypto` into the build system. There may be other problems.

The ARM code does not yet validate UTF-8, but it does parse strings and numbers (without any fast number handling).

**Comment by lemire** [comment]
I fixed '-march=armv8.2-a+crypto' so that we can get a straight compile with "make".

**Comment by lemire** [comment]
We need to (1) add the UTF-8 validation (2) run our tests (make test) and have them actually pass... 

Once this is done, we'll be able to assess the performance.

**Comment by lemire** [comment]
ping @ioioioio : please have a look at this issue.

**Comment by lemire** [comment]
@ioioioio : can you try to complete the NEON port and see whether we can pass our tests?

**Comment by lemire** [comment]
Done thanks to @geofflangdale and @ioioioio

**Comment by lemire** [comment]
Blog post with some numbers:

https://lemire.me/blog/2019/07/10/parsing-json-using-simd-instructions-on-the-apple-a12-processor/

**Comment by lemire** [comment]
Another related blog post (more numbers):

Parsing JSON quickly on tiny chips (ARM Cortex-A72 edition)
https://lemire.me/blog/2019/07/11/parsing-json-quickly-on-tiny-chips-arm-cortex-a72-edition/
