### ISSUE TITLE
Update README documentation to account for the new namespace

### ISSUE THREAD

**Issue by lemire** [lemire/simdjson#203]
Thanks to a PR by @ioioioio @lcdavid94, it looks like we are now under a C++ namespace. Yet the documentation (README) has not yet been updated.

https://github.com/lemire/simdjson/issues/59

**Comment by lemire** [comment]
@ioioioio Do you want to handle this one?

**Comment by ioioioio** [comment]
sure

**Comment by lemire** [comment]
Closed by @ioioioio's PR.
