### ISSUE TITLE
singleheader/simdjson.cpp got removed?

### ISSUE THREAD

**Issue by luizperes** [lemire/simdjson#215]
`singleheader/simdjson.cpp` got removed in the commit https://github.com/lemire/simdjson/commit/977f57fd370c34f75d86f22d6402d780bb958b1c#diff-3c06b7a2177788ae34d76dd4ba6f3759 yesterday and breaks the example `amalgamation_demo.cpp` inside the `singleheader` folder, along with the possibility of using simdjson with a single header and a single implementation file, which is the case for [simdjson_nodejs](https://github.com/luizperes/simdjson_nodejs).

This is a blocker for me for two issues I was about to solve: https://github.com/luizperes/simdjson_nodejs/issues/16 and https://github.com/luizperes/simdjson_nodejs/issues/15.

Not sure if that was an accident or not, could you help me solve that?

Thanks!

**Comment by lemire** [comment]
Will fix today. No problem. Must have been a mistake.

Can you set your dependency to one of our releases? This would make things more robust on your end.

**Comment by lemire** [comment]
Fixed just now. I do recommend that you set your dependencies to a release for better stability.

**Comment by luizperes** [comment]
You’re right, will do it today, thanks!

**Comment by lemire** [comment]
@luizperes  We are working toward a new release (version 0.2), it will bring many new features... it will run on ARM processors, and so forth.
