### ISSUE TITLE
Provide a DOM creation option

### ISSUE THREAD

**Issue by michaeleisel** [lemire/simdjson#219]
It would be nice for simdjson to allow a stage 3 for creation of a DOM, like rapidjson and others do. also, i wonder if benchmarking that against rapidjson would be more accurate

**Comment by michaeleisel** [comment]
perhaps it doesn't need to be split out into a stage 3, integration in stage 2 could be faster. but the general idea is just to create a DOM

**Comment by lemire** [comment]
To be clear, here is what I mean by DOM: an ordered tree structure where each node (value, object, array) in the JSON document is accessible via an API.  In this sense, the result of the parsing in simdjson is a DOM. Our API is quite similar to RapidJSON and others (and we are implementing JSON pointers, and other features). In some ways, our core API is arguably superior to that of RapidJSON.

The main difference with RapidJSON is that it is a *static* DOM (that cannot be manipulated). The backend of RapidJSON works much like we do... it does memory allocation in block, which is basically equivalent to our tape structure.

Evidently, RapidJSON has more features as it is not solely a parser, but a whole framework to handle JSON, whereas simdjson is *mostly* just a parser.

Even so, our current tape data structure could 'easily' be replaced by some other data structure. E.g., it would be possible to plug simdjson in RapidJSON... the main reason that this is difficult is that RapidJSON does not support a pluggable parser.

I am going to close this issue. Please reopen it if you think it holds by making it more precise.

I *think* that what you mean is that simdjson should produce a mutable DOM.

**Comment by lemire** [comment]
The following commit should help clarify the issue...

https://github.com/lemire/simdjson/commit/abdf81b39b3b4116ee570cc4ef1731163685c5cd

We have a full DOM with iterators, and JSON Pointer support is upcoming.

**Comment by michaeleisel** [comment]
Yes, this issue is a mistake due to a few misunderstandings of mine. I was under the impression that RapidJSON uses a hash for dictionaries to go from key -> value. I then thought that that was the standard way to do DOM parsing. Instead, it appears to use an array structure like simdjson does. Thank you for the clarification.

It is interesting that they both use array structures, as random access (which is what, e.g., swift's Decodable protocol requires) is O(n). If the client puts the object's member fields in the same order as the json dictionaries do, then it can be fast anyways. Otherwise, it could use a hash, or something like a trie generated for each type that traverses using the key and has nodes as offsets to where the data is within a dynamically generated struct.

**Comment by michaeleisel** [comment]
By random access I mean lookup by key

**Comment by lemire** [comment]
Yes, I understand what you mean. 

The big-O analysis only works if n is large. If you have JSON objects with 100 keys, then... yes, this becomes a concern. But my experience with JSON is that this is not common. There are usually few keys.

A hash table can be slower than array if there are few keys. It will certainly use more memory and be have more overhead.

So far, all tests I have run suggests that querying the DOM in simdjson or RapidJSON is super fast... much, much faster than parsing the DOM. 

You are right though this aspect of the problem needs to be better studied and documented... however, we have work to do in simdjson to optimize better even the current design.
