### ISSUE TITLE
Negative numbers on root do not parse.

### ISSUE THREAD

**Issue by ioioioio** [lemire/simdjson#221]
Documents do not parse when they only contain a single negative number that is not into an array or an object.

example: 
char* json = "-1"

**Comment by lemire** [comment]
Can you double check? I cannot verify this bug.

**Comment by ioioioio** [comment]
Do you mean that you tried to reproduce the bug and it did not work?

I already spent some time to test that bug, since it seemed really unexpected. I'll try again tomorrow.

**Comment by lemire** [comment]
Exactly I cannot verify that this is a bug.

**Comment by lemire** [comment]
This issue has been verified and fixed in a PR (that is to be merged).
