### ISSUE TITLE
update vcpkg to simdjson 0.2.1

### ISSUE THREAD

**Issue by lemire** [lemire/simdjson#245]
We have a new release. This new version brings about support for 64-bit ARM.

I think that we need to update our vcpkg.

https://github.com/microsoft/vcpkg/blob/be4158fb89045319f19d83d08b851e6e694b5b12/ports/simdjson/portfile.cmake

@myd7349 can you help?

**Comment by myd7349** [comment]
@lemire Sure!

**Comment by lemire** [comment]
@myd7349 Version 0.2.1 should work for DLL releases.

**Comment by myd7349** [comment]
Hi! @lemire This issue can be safely closed now.

**Comment by lemire** [comment]
+1
