### ISSUE TITLE
update debian to simdjson 0.2.0

### ISSUE THREAD

**Issue by lemire** [lemire/simdjson#246]
We have a new release of simdjson that brings about support for 64-bit ARM and runtime dispatching. We need to update our debian package to simdjson 0.2.0.

@cdluminate  can you help?

**Comment by cdluminate** [comment]
@lemire Sure.

**Comment by cdluminate** [comment]
https://tracker.debian.org/pkg/simdjson simdjson 0.2.0 was uploaded to Debian unstable. Later on I will upload it to buster backports.

**Comment by lemire** [comment]
We are going to close this issue. Thanks @cdluminate.
