### ISSUE TITLE
Feature request: C API

### ISSUE THREAD

**Issue by SunDoge** [lemire/simdjson#249]
After upgrading to 0.2.0, many functions become inline, which makes it difficult to develop bindings for simdjson, because inline functions are unable to link to. Though I can modify the source code in my project vendor by using regex to remove all `inline` keyword, it will prevent me from linking to the shared library in the system path.

I suggest externing some API in C with a common prefix such as `sj_` while keeping functions in Cpp inline to preserve the advantage of the inline function.

**Comment by lemire** [comment]
@SunDoge 

I guess you refer to the navigation of the DOM? Having these functions be inline is critical to good performance when you are browsing through thousands of nodes (but I am sure you understood this).

> Though I can modify the source code in my project vendor by using regex to remove all inline keyword

Please don't do this! Let us find a way to make it work directly instead. We should issue a 0.2.1 version instead.

> I suggest externing some API in C with a common prefix such as sj_ while keeping functions in Cpp inline to preserve the advantage of the inline function.

I am not sure I understand what you mean...

What is certainly possible is to take all inline functions that we want to wrap and create a no-inline version (with definition in a non-header file). Then the no-inline function can just call the inline function.

Would it work for you?

It is not super elegant but there may be a way to make it not too ugly.

Comments invited.

cc @ioioioio

**Comment by lemire** [comment]
Regarding a C API... can you elaborate? The main issue I see is that we are relying on a ParsedJson class... It is not obvious how this could interoperate nicely with C.

**Comment by SunDoge** [comment]
I have to struggle with my paper until September, so I can't reply in a timely manner.

Implementing those inline functions in Rust is dangerous, but marking them as `#[inline]` in Rust may have a performance advantage, so I'll keep trying.

For example, [https://github.com/apache/incubator-mxnet/blob/master/include/mxnet/c_api.h](https://github.com/apache/incubator-mxnet/blob/master/include/mxnet/c_api.h)

For object A:
1. `A_new()` to init the object handle, `A_destroy(A*)` to delete the pointer safely.
2. Member function of A has a `A_func(A*)` version.

So that other language can use cffi to bind the shared library with standard api.

**Comment by SunDoge** [comment]
I'll reopen it if anyone has the same request.

**Comment by sunnygleason** [comment]
@lemire I'm not quite sure, I'd like to hear @SunDoge 's explanation.

Maybe it is as easy as replacing "inline" with a macro def that @SunDoge can
"ifdef out" in the Rust/C bindings? (I'm guessing it can't be that easy) :)

One similar aspect I've encountered is trying to write unit tests for
ported functions to other languages/architectures (rust/SSE42) to
verify intermediate results/function-level correctness. (I've found
that the test suite is great for uncovering errors but not pinpointing
bugs in the impl -- I didn't look around in the codebase much though,
maybe I missing finer-grained tests...)

In any event, thank you for your consideration/thoughtfulness!

**Comment by SunDoge** [comment]
@lemire @sunnygleason I'll be back after finishing my paper on Sept. 6th. I'll write a thin wrapper myself and see if it works.

**Comment by d4tocchini** [comment]
@SunDoge @lemire 

any movement on this or something I can be pointed to?

**Comment by lemire** [comment]
@d4tocchini 

> any movement on this or something I can be pointed to?

This issue is closed.

I think that the original concern is that wrapping simdjson for use in other languages would be difficult. However, experience taught us that it was not the case. There are many simdjson wrappers, and our C++ API is not proving to be a problem. Quite the contrary, since 0.3, we have had multiple compliments regarding how nice it is.

**Comment by SunDoge** [comment]
Hi, @d4tocchini 

You can design one by yourself, for example [gist](https://gist.github.com/SunDoge/4287ce6e128346290f0414ae88696ab5). 

I will be glad to see a pr, though I have switched to another solution. The difficulty is that you have to specialize all generics and use C types only.

**Comment by d4tocchini** [comment]
@SunDoge, thanks.  What sort of solution did you go with?

**Comment by SunDoge** [comment]
@d4tocchini  I use [cxx](https://github.com/dtolnay/cxx). It generates some template code automatically.

**Comment by Dan-Do** [comment]
Hello, where can I find the C API? I want to create Crystal-lang binding for this awesome library.

**Comment by Dan-Do** [comment]
> Regarding a C API... can you elaborate? The main issue I see is that we are relying on a ParsedJson class... It is not obvious how this could interoperate nicely with C.

Hello @lemire, regarding C API/wrapper you can look at this https://github.com/pavelmash/simdjson_pas/tree/main/lib
Many other languages only support C because C++ mangled is too complicated. For example I am coming from Crystal-lang https://github.com/crystal-lang/crystal/issues/3098

**Comment by lemire** [comment]
@Dan-Do If you'd like to contribute C wrappers, please consider producing a pull request.

**Comment by Dan-Do** [comment]
@lemire Thank you. I'm comming from high programming language and be novice in C/C++, but I will try my best.

**Comment by kassane** [comment]
There is also a project in development using zig:
https://github.com/travisstaloch/simdjzon
Just like C language it is also easier to interop.

**Comment by IngwiePhoenix** [comment]
Has there been any movement on this?

I want to use this from V, which has the ability to interact with C. So before poking around, I thought I'd look into the issues tab and found this. :)

Thanks!
