### ISSUE TITLE
Dynamic library broken under Windows due to runtime dispatching: unresolved external symbol simdjson::json_parse_ptr

### ISSUE THREAD

**Issue by myd7349** [lemire/simdjson#250]
Hi! I am tring to update vcpkg's `simdjson` to v0.2.0. And it seems that dynamic library support on Windows with MSVC is broken:
```
json2json.cpp.obj : error LNK2001: unresolved external symbol "int (__cdecl* simdjson::json_parse_ptr)(unsigned char const *,unsigned __int64,class simdjson::ParsedJson &,bool)" (?json_parse_ptr@simdjson@@3P6AHPEBE_KAEAVParsedJson@1@_N@ZEA)
tools\json2json.exe : fatal error LNK1120: 1 unresolved externals
...
pointercheck.cpp.obj : error LNK2001: unresolved external symbol "int (__cdecl* simdjson::json_parse_ptr)(unsigned char const *,unsigned __int64,class simdjson::ParsedJson &,bool)" (?json_parse_ptr@simdjson@@3P6AHPEBE_KAEAVParsedJson@1@_N@ZEA)
tests\pointercheck.exe : fatal error LNK1120: 1 unresolved externals
...
basictests.cpp.obj : error LNK2001: unresolved external symbol "int (__cdecl* simdjson::json_parse_ptr)(unsigned char const *,unsigned __int64,class simdjson::ParsedJson &,bool)" (?json_parse_ptr@simdjson@@3P6AHPEBE_KAEAVParsedJson@1@_N@ZEA)
tests\basictests.exe : fatal error LNK1120: 1 unresolved externals
```
In `simdjson`'s CMakeLists.txt, [```WINDOWS_EXPORT_ALL_SYMBOLS```](https://cmake.org/cmake/help/latest/prop_tgt/WINDOWS_EXPORT_ALL_SYMBOLS.html) is used to automatically export symbols found in the dll:
https://github.com/lemire/simdjson/blob/349068dcda596261dba68a4238bbbc0af4c66ef3/src/CMakeLists.txt#L66

Unfortunately, the document of `WINDOWS_EXPORT_ALL_SYMBOLS` also says that:
>For global data symbols, __declspec(dllimport) must still be used when compiling against the code in the .dll. All other function symbols will be automatically exported and imported by callers. 

`json_parse_ptr` is defined as a data symbol here:
https://github.com/lemire/simdjson/blob/349068dcda596261dba68a4238bbbc0af4c66ef3/include/simdjson/jsonparser.h#L30

It is a data symbol, so that is why there are so many `unresolved externals` errors.

`CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS` has been discarded for some other reasons in `vcpkg`: https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#do-not-add-cmake_windows_export_all_symbols

So, I suggest we may consider discarding `WINDOWS_EXPORT_ALL_SYMBOLS` as well.

I think we have two choices here:
1. Discard dynamic library support on Windows.
2. Use `__decpspec()` to decorate all the public APIs, like what I did in:
   - [libfoo_v2](https://github.com/myd7349/Ongoing-Study/tree/master/cpp/CMake/libfoo_v2)
   - [libfoo_v3](https://github.com/myd7349/Ongoing-Study/tree/master/cpp/CMake/libfoo_v3)

**Comment by lemire** [comment]
What seems immediately obvious to me is that we need to add tests for dynamic library support. We have CI tests under Windows... but not for dynamic library.

@myd7349  Would you be willing to prepare a PR or, at least, elaborate on your proposal?

**Comment by lemire** [comment]
The bug is verified: https://ci.appveyor.com/project/lemire/simdjson

**Comment by lemire** [comment]
cc @ioioioio

**Comment by lemire** [comment]
cc @jkeiser

**Comment by lemire** [comment]
I think that illustrative logic from @myd7349 's example  is found in this file...

https://github.com/myd7349/Ongoing-Study/blob/3d28ccb7e50e344dc2599269726e2ddd581880f0/cpp/CMake/libfoo_v2/include/libfoo/foo.h

**Comment by lemire** [comment]
@myd7349 BTW, we do want to export json_parse_ptr as a function pointer.

**Comment by lemire** [comment]
Or maybe not.

**Comment by lemire** [comment]
Ok. I have a possible fix in this PR...
https://github.com/lemire/simdjson/pull/252

It builds.

However ctest fails because the DLL is not found. It is a path issue.

**Comment by lemire** [comment]
Ok. Need to copy over the DLL... I think it works now.

**Comment by lemire** [comment]
@myd7349 We can build a DLL and link against it on Windows. This is now part of our CI. Hopefully, this will solve the issue you encountered.

Of course, it is still possible to change how we generate the DLL.

I will shortly issue a new release.
