### ISSUE TITLE
Terrible performance regression due to commit "Replace macros by include files"

### ISSUE THREAD

**Issue by lemire** [lemire/simdjson#258]
We have just merged a commit that drops our performance in stage 1 very significantly (replacing macros by include files):

before:
```
simdjson$ git checkout bd9628df93851c2baf6316378a91a0b7dff32a22
Previous HEAD position was 349068d... Update README.md
HEAD is now at bd9628d... Producing a new release
dlemire@skylake:~/CVS/github/simdjson$ make parse && ./parse jsonexamples/twitter.json
g++-8 -msse4.2 -mpclmul  -std=c++17   -Wall -Wextra -Wshadow -Iinclude  -Ibenchmark/linux  -O3 -o parse src/jsonioutil.cpp src/jsonparser.cpp src/simdjson.cpp src/stage1_find_marks.cpp src/stage2_build_tape.cpp src/parsedjson.cpp src/parsedjsoniterator.cpp benchmark/parse.cpp
number of iterations 1000
number of bytes 631515 number of structural chars 55264 ratio 0.088
mem alloc instructions:       1207 cycles:        815 (0.08 %) ins/cycles: 1.48 mis. branches:          4 (cycles/mis.branch 193.66) cache accesses:      28010 (failure          0)
 mem alloc runs at 0.00 cycles per input byte.
stage 1 instructions:    1743028 cycles:     541350 (51.69 %) ins/cycles: 3.22 mis. branches:       1536 (cycles/mis.branch 352.38) cache accesses:      28010 (failure          0)
 stage 1 runs at 0.86 cycles per input byte.
stage 2 instructions:    1490175 cycles:     505102 (48.23 %) ins/cycles: 2.95 mis. branches:       1662  (cycles/mis.branch 303.88)  cache accesses:      51482 (failure          0)
 stage 2 runs at 0.80 cycles per input byte and 9.14 cycles per structural character.
 all stages: 1.66 cycles per input byte.
Estimated average frequency: 3.719 GHz.
Min:  0.000281597 bytes read: 631515 Gigabytes/second: 2.24262
```

after:
```
simdjson$ git checkout 2a24567370a7a96aacf2aa4ebf4548c817450516
Previous HEAD position was bd9628d... Producing a new release
HEAD is now at 2a24567... Replace macros by include files (#236) (#248)
dlemire@skylake:~/CVS/github/simdjson$ make parse && ./parse jsonexamples/twitter.json
g++-8 -msse4.2 -mpclmul  -std=c++17   -Wall -Wextra -Wshadow -Iinclude  -Ibenchmark/linux  -O3 -o parse src/jsonioutil.cpp src/jsonparser.cpp src/simdjson.cpp src/stage1_find_marks.cpp src/stage2_build_tape.cpp src/parsedjson.cpp src/parsedjsoniterator.cpp benchmark/parse.cpp
number of iterations 1000
number of bytes 631515 number of structural chars 55264 ratio 0.088
mem alloc instructions:       1207 cycles:        750 (0.06 %) ins/cycles: 1.61 mis. branches:          2 (cycles/mis.branch 313.73) cache accesses:      29845 (failure          0)
 mem alloc runs at 0.00 cycles per input byte.
stage 1 instructions:    2219082 cycles:     798002 (61.39 %) ins/cycles: 2.78 mis. branches:       1662 (cycles/mis.branch 479.89) cache accesses:      29845 (failure          0)
 stage 1 runs at 1.26 cycles per input byte.
stage 2 instructions:    1490175 cycles:     501151 (38.55 %) ins/cycles: 2.97 mis. branches:       1546  (cycles/mis.branch 324.08)  cache accesses:      54613 (failure          0)
 stage 2 runs at 0.79 cycles per input byte and 9.07 cycles per structural character.
 all stages: 2.06 cycles per input byte.
Estimated average frequency: 3.711 GHz.
Min:  0.000350329 bytes read: 631515 Gigabytes/second: 1.80263
```

It is bad enough to be considered a bug.

cc @ioioioio

**Comment by lemire** [comment]
Note that this commit is *after* release 0.2.1, so we do not have this regression in a release.

**Comment by lemire** [comment]
Link to the guilty commit...

https://github.com/lemire/simdjson/commit/2a24567370a7a96aacf2aa4ebf4548c817450516

**Comment by lemire** [comment]
cc @jkeiser

**Comment by lemire** [comment]
This one is a bit of a puzzler. I was not expecting any performance difference from that commit. Something specific is hurting us.

**Comment by lemire** [comment]
Note that the problem *only* affects stage 1.

**Comment by lemire** [comment]
Here is a hint: it affects ARM NEON as well. So it is not caused by runtime dispatch.

**Comment by ioioioio** [comment]
I had to leave early today for an exam. Otherwise I consider this a serious issue and I wish I had got the time to look for a fix.

I have not deleted the branch on which I worked on this (https://github.com/lemire/simdjson/tree/suppress_macros). I think there might be good clues on it. For example, I remember I have tested for performances at least just before I did the first commit. 

I'll check this tomorrow for sure.

**Comment by ioioioio** [comment]
well..... in fact my tests show performance regression from the first commit on the branch.

**Comment by lemire** [comment]
Thanks @ioioioio 

No blame here.

**Comment by jkeiser** [comment]
Man ... how?

Once again, performance shows us that our intuitions about it are wrong.

**Comment by jkeiser** [comment]
Here's a link to [the original PR](https://github.com/lemire/simdjson/pull/248/commits), so we can see the commits.

@ioioioio I can't check it right now, but just to confirm, are you saying that the [clang-format](https://github.com/lemire/simdjson/pull/248/commits/1c21338cdd8dadc91e1af6999c8f432eb33d0102) commit shows the regression?

**Comment by ioioioio** [comment]
this commit: https://github.com/lemire/simdjson/commit/19fcb68c61f91702ce2196045bbce7b206343b9b

**Comment by jkeiser** [comment]
On first scan, the only textual difference I see that ought to make a difference to the *code* is [a new if statement in the call to flatten_bits](https://github.com/lemire/simdjson/commit/19fcb68c61f91702ce2196045bbce7b206343b9b?diff=split&w=1#diff-cec8a5fb1819dce9c4b8c2f41000a223R197-R201). Maybe it's not being optimized away and we're seeing a misprediction?

**Comment by ioioioio** [comment]
I tried to just delete it and compile only with the haswell::flatten_bits. Was not better.

I pushed a branch with a quick fix. I just reverted the changes on stage1. I think it might help to identify the problem.
https://github.com/lemire/simdjson/tree/performance_regression_quick_fix

**Comment by jkeiser** [comment]
Cool. I built a PR to templatize flatten_bits, which it seems like we should just do anyway. Unfortunately, I can't dump anymore time to it until late tonight.

**Comment by jkeiser** [comment]
BTW, if the revert fixes the problem and removing the if doesn't, it's better to just revert than pile my templatization on top.

**Comment by ioioioio** [comment]
I have a [branch](https://github.com/lemire/simdjson/tree/performance_issue_fix(%23258)) with no performance issue. It only needs cleaning and an amalgamation fix.

The sad part is we might never know what was the problem.

**Comment by lemire** [comment]
@ioioioio Surely, we can figure out the cause!!! :-)

**Comment by ioioioio** [comment]
That branch fixes the performance regression: https://github.com/lemire/simdjson/tree/issue258_fix_performance.

If we compare to master, we notice there are not a lot of differences:
1. find_structural_bits_64 is really_inline
2. find_structural_bits_64 selects flatten_bits with a template argument (I'm not sure to understand why it helps, though)

[PR#262](https://github.com/lemire/simdjson/pull/262) will fix one of these two points.

**Comment by lemire** [comment]
@ioioioio Thanks.

1. Yes, inlining is super important during stage 1. That alone might explain the performance regression.

2. I have not looked at the code but if we have a runtime branch, even if it is easy-to-predict, it could harm performance because the binary gets fatter and there is more jumping around. That alone should not explain the regression we saw, however.

**Comment by lemire** [comment]
Closing given recent PR fixing this issue.

**Comment by lemire** [comment]
The fix is from https://github.com/lemire/simdjson/pull/262

I manually verified the fix.
