### ISSUE TITLE
Check for perf regression in CI

### ISSUE THREAD

**Issue by jkeiser** [lemire/simdjson#260]
I do wonder if any of the many CI solutions out there handles perf graphing and regression checking over time. Even if it's not first-class, we could do a CI run that benches the code before and after the patch in the same container.

**Comment by lemire** [comment]
@jkeiser  Yes. Currently, I do it by hand from time to time. It would be great to automate the process... 

It is not support hard probably. You run the benchmark, grab some numbers. Then you do a "git checkout" and you grab a known release, then you compare the performance. If the performance differs too much, then you flag it.

cc @ioioioio

**Comment by lemire** [comment]
Closing
