### ISSUE TITLE
`max` and `min` disruptive marco in <windows.h>

### ISSUE THREAD

**Issue by Skyprophet** [lemire/simdjson#269]
For portability, simdjson includes <windows.h> in `jsonparser.h`. However, it is super disruptive when user want to use `std::min` or `std::max`.

The solution is to use `NOMINMAX` macro to suppress `min` and `max` macro definitions in <windows.h>.

Since `simdjson` does not rely on these `min` and `max` macros at all. I think it is a good idea to define `NOMINMAX` by default.

**Comment by lemire** [comment]
Can you issue a PR?

**Comment by lemire** [comment]
Note: we may not beed windows.h anymore!

**Comment by Skyprophet** [comment]
If it is not required, the best way to deal with it is to remove it directly. Anyway, I can do a PR introducing the NOMINMAX macro.

**Comment by lemire** [comment]
Thanks.

**Comment by lemire** [comment]
The header was removed without harm. I think we agree that it is the best solution. Closing.
