### ISSUE TITLE
Capability to parse JSON batches

### ISSUE THREAD

**Issue by Skyprophet** [lemire/simdjson#274]
It would be nice to see a feature which can take multiple JSON document in a batch so that user can validate and parse them together.

It may also beneficial for performance as the overall padding amount for aligning with SIMD instructions may be significantly reduced when parsing large batches.

**Comment by lemire** [comment]
Could be addressed along with https://github.com/lemire/simdjson/issues/188

**Comment by Skyprophet** [comment]
Yeah, it would also be nice to support cases where JSON documents are not delimited by new lines.

**Comment by lemire** [comment]
I don't expect we will enforce the new line separation.
