### ISSUE TITLE
Question: fesibility to use the same technique to speed up XML parsing

### ISSUE THREAD

**Issue by the-oaks** [lemire/simdjson#297]
the performance of simdjson is very impressive, giving JSON is somehow similar to XML, is it possible to apply some of the techniques used in simdjson for XML parsing?

**Comment by lemire** [comment]
@the-oaks We expect so, yes. However, xml has a more complicated grammar so it would be a bit more work.

**Comment by the-oaks** [comment]
@lemire thanks for the reply, could you please share some hints on how could we get started on this? e.g. what would be the key functions/code that we need to update? thanks

**Comment by lemire** [comment]
The best way to get started is probably to read the paper... https://arxiv.org/abs/1902.08318 Then one should identify the structural characters...

**Comment by the-oaks** [comment]
thanks very much for the hints :)
