### ISSUE TITLE
ARM neon_movemask_bulk losing half the mask?

### ISSUE THREAD

**Issue by jkeiser** [lemire/simdjson#309]
I'm trying to follow the ARM movemask code, and I simply can't figure out how we aren't losing all information about the high bytes. [From neon_movemask_bulk](https://github.com/lemire/simdjson/blob/master/src/arm64/simd_input.h#L20):

```c++
really_inline uint64_t neon_movemask_bulk(uint8x16_t p0, uint8x16_t p1,
                                          uint8x16_t p2, uint8x16_t p3) {
  const uint8x16_t bit_mask = {0x01, 0x02, 0x4, 0x8, 0x10, 0x20, 0x40, 0x80,
                              0x01, 0x02, 0x4, 0x8, 0x10, 0x20, 0x40, 0x80};
  uint8x16_t t0 = vandq_u8(p0, bit_mask);
  uint8x16_t t1 = vandq_u8(p1, bit_mask);
  uint8x16_t t2 = vandq_u8(p2, bit_mask);
  uint8x16_t t3 = vandq_u8(p3, bit_mask);
  uint8x16_t sum0 = vpaddq_u8(t0, t1);
  uint8x16_t sum1 = vpaddq_u8(t2, t3);
  sum0 = vpaddq_u8(sum0, sum1);
  sum0 = vpaddq_u8(sum0, sum0);
  return vgetq_lane_u64(vreinterpretq_u64_u8(sum0), 0);
}
```

All the operations are restricted to each 8-bit lane with no lane crossing. The final result just returns the bottom 64 bits. What am I missing? I'm sure I'm missing something simple. But from [the stackoverflow answer on the subject](https://stackoverflow.com/a/12383618), I think some of those addq_u8's were meant to be addq_u32 / addq_u64 (the trick being to widen the addition each time you do it, which we're not doing).

**Comment by jkeiser** [comment]
We appear to have been u8 [for quite a while](https://github.com/lemire/simdjson/blob/1176725af79db8222f48ee1678a9db7c0e58e772/include/simdjson/stage1_find_marks.h#L86), so I'm sure it's just me missing something--I just can't figure what, and I don't have an ARM machine sitting around to find out. Feel free to close with extreme prejudice if I'm off base here, I figured I'd bring it up and maybe at least learn something :)

**Comment by jkeiser** [comment]
Ah, finally found https://branchfree.org/2019/04/01/fitting-my-head-through-the-arm-holes-or-two-sequences-to-substitute-for-the-missing-pmovmskb-instruction-on-arm-neon/ . Closing.

**Comment by lemire** [comment]
:-)

Note to self: This is another great example of code that is incomprehensible even to veteran programmers.
