### ISSUE TITLE
Incomplete error_strings map

### ISSUE THREAD

**Issue by Archie3d** [lemire/simdjson#318]
`UNCLOSED_STRING` error code is missing in `error_strings` map that causes out of range exception when getting error message.

Better solution maybe is to make `error_message(const int error_code)` check the code is actually in the map, and return some `"Unknown error"` style string.

**Comment by lemire** [comment]
This will be fixed in the next release.

**Comment by lemire** [comment]
Fixed by https://github.com/lemire/simdjson/pull/319
