### ISSUE TITLE
Replace usage of string_view by a custom string class

### ISSUE THREAD

**Issue by seanmiddleditch** [lemire/simdjson#32]
From the README:

```
std::string_view p = get_corpus(filename);
...
// You can safely delete the string content
free((void*)p.data());
```

This is a misuse of `string_view`'s semantics, and runs afoul of various rules that will be flagged by static analyzers, and we don't want students seeing this and copying it without understanding that it's not recommended (`string_view` is not just a blanket replacement for `char*`!).

For the sake of the example, it'd probably be better to just use an idiomatic `std::string` and illustrate that the parsed document can still be used after that string goes out of scope.

**Comment by lemire** [comment]
A simple std::string would come with an unnecessary and measurable performance penalty. What several other libraries do is to create their own string objects. 

What I invite folks to do is propose a zero-overhead (i.e. no unnecessary copy, no reallocate) that is functionally equivalent to what we are doing right now... 

https://github.com/lemire/simdjson/blob/master/src/jsonioutil.cpp


It is should be possible with custom memory allocators.

**Comment by seanmiddleditch** [comment]
> A simple std::string would come with an unnecessary and measurable performance penalty

.... for the README example? I'm not proposing that simdjson itself use the `std::string` itself, I'm just saying for the README example to use it as the storage for the example input rather than abusing `string_view` the way it is. :)

If you're morally opposed to `std::string` even in the example, perhaps just use a plain `char*` variable instead of misusing `string_view` that way.

**Comment by lemire** [comment]
The example has to match how one could use the code. You cannot use std::string. You also can’t use a C string.

A string_view is explicitly meant to serve as a wrapper. 

If one has a better API that comes at no performance cost... that’d be great.

**Comment by seanmiddleditch** [comment]
> The example has to match how one could use the code. You cannot use std::string. You also can’t use a C string.

... Of *course* you can use a `std::string` or `char*`. I mean, obviously. :|

You can construct a `string_view` from any sequence of characters no matter how they're stored. You can implicitly convert a `std::string` into a `string_view`. You can convert a `char*` into a `string_view`. You can convert a `char[N]`, `QString`, `CString`, `MyCustomString`, or `vector<char>` into a `string_view`; some of them implicitly, some of them with an explicit construction, but you can handle _any_ sequence of `char`s. That's one of the whole points of `string_view`! :)

This has _absolutely nothing to do with simdjson or its API or its implementation or speed_! This is _only_ about how the README example is shoving an owned `char*` sequence into a `string_view` and then calling `free(sv.data())` which is a violation of the semantics of `string_view` and will run afoul of static analysis checkers (e.g. the GSL checkers).

Here's a better example:

```
ParsedJson pj;
{
  std::string p = get_corpus(filename);
  pj.allocateCapacity(p.size()); // allocate memory for parsing up to p.size() bytes
  bool is_ok = json_parse(p, pj); // do the parsing, return false on error
}
// you can safely still use pj here even though p went out of scope
```

**Comment by lemire** [comment]
I don’t think this code sample would work.

**Comment by lemire** [comment]
I added the label "help wanted".

**Comment by StephanDollberg** [comment]
Why would that example not work? Just had a look at the repo and that example threw me off immediately.

**Comment by StephanDollberg** [comment]
Ah I see now, because get_corpus gives you aligned memory. In that case you should a RAII wrapper class for your corpus. Having people manually free the corpus is not very C++y. 

The single header example is already missing that and leaking memory.

**Comment by lemire** [comment]
Possibly we could use `std::unique_ptr<char, decltype(&free)>` instead.

**Comment by lemire** [comment]
Closing. An upcoming merge will introduce a `padded_string`.
