### ISSUE TITLE
Can I build the internal tape from a string_view and avoid memory allocations?

### ISSUE THREAD

**Issue by jplauri** [lemire/simdjson#334]
I have large `std::string` that contains multiple moderately-sized JSON files separated by newline characters. Ideally, when parsing relevant pieces of information from these JSONs, I'd like to avoid extra memory allocations. In principle, one solution would be to take `string_view`s over the large string and parse the files by merely moving a pointer.

Is it possible to use simdjson for this, i.e., can I only pay for the construction of the internal tape, so that a `string_view` is only read from?

**Comment by lemire** [comment]
At a glance, your issue seems closely related to issue https://github.com/lemire/simdjson/issues/188 

> Is it possible to use simdjson for this, i.e., can I only pay for the construction of the internal tape, so that a string_view is only read from?

I am not sure I understand your concern. The simdjson does not modify the input, so if you pass it a string of characters, it is going to be "only read from", by design.

**Comment by jplauri2** [comment]
Oh, I see. This is also exactly what I was looking for. Thanks for the pointer!

**Comment by jplauri** [comment]
Oh, I see. This is also exactly what I was looking for. Thanks!
