### ISSUE TITLE
Optimize away page walking 

### ISSUE THREAD

**Issue by lemire** [lemire/simdjson#393]
For large files, we are often limited by page walking.

**Comment by jkeiser** [comment]
Can you elaborate on this, for someone who hasn't written a memory manager/allocator? Is this on reading the input, the write to ParsedJson, the read from ParsedJson, all of the above? I'm unclear how you optimize this away, too.

**Comment by lemire** [comment]
If you are reading data sequentially or somewhat sequentially, the hardware prefetcher may stay on top of you and keep the cache misses to a minimum. However, most hardware prefetchers don't prefetch beyond the page boundary. Hitting a new page may trigger a TLB miss and thus an expensive page walking. Ideally, you ought to "prefetch" sufficiently long before the new page so that the TLB miss can happen while the rest of your code finishes the existing page.

Furthermore, you should be minimizing the number of pages you have to touch. This is actually where we can do the most good in the near future.

**Comment by lemire** [comment]
I am going to close this issue since it is potentially misleading.
