### ISSUE TITLE
Support null characters in strings

### ISSUE THREAD

**Issue by geofflangdale** [lemire/simdjson#40]
There seem to be some strong opinions out there that NUL chars in JSON strings should be supported. This would suggest that we maintain strings by length - possibly keep offset+length on the tape? Or start each string with a length field.

**Comment by lemire** [comment]
This is not very difficult but requires a small change to the string tape.

**Comment by TkTech** [comment]
Having the length of the string exposed (since it's calculated at least once in simdjson already) would be a great performance boost for pysimdjson, since the conversion from `const char *` to `unicode` can be optimized when the length is known ahead of time.

**Comment by lemire** [comment]
@TkTech  Just to clarify your comments... the char* we store are already unicode (UTF8). Maybe you mean some other unicode encoding?

**Comment by TkTech** [comment]
CPython (usually) does not use UTF-8 internally, but rather something closer to UTF-16. When going from simdjson to python we need to convert those UTF-8 strings into `unicode` objects that the Python interpreter understands using [PyUnicode_DecodeUTF8](https://docs.python.org/3/c-api/unicode.html#c.PyUnicode_DecodeUTF8).

When the length of the string isn't known Cython will wrap everything in `strlen`, which when you have a document with thousands of strings will add quite a bit of overhead, especially if parts of the document are converted into Python objects multiple times.

**Comment by lemire** [comment]
Ah yes, UTF-16.

**Comment by lemire** [comment]
Fixed with https://github.com/lemire/simdjson/pull/101
