### ISSUE TITLE
move_to_key & move_to_index not going back to the uppper depth if the desired key is not found

### ISSUE THREAD

**Issue by ukabuer** [lemire/simdjson#420]
According to the documentation, `move_to_key()` and `move_to_index()` should go back to the original depth if the desired key is not found.

However, it seems that these functions forget to invoke `up()`?

https://github.com/lemire/simdjson/blob/0dc80ccf21882958227a30eb30f745a72a1424a2/include/simdjson/parsedjsoniterator.h#L325

**Comment by lemire** [comment]
Thank you. I have added tests as well and I confirm the fix.

**Comment by lemire** [comment]
@ukabuer I will gladly credit you if you give me your actual name.
