### ISSUE TITLE
Is it safe to mutate string values after parsing?

### ISSUE THREAD

**Issue by michaeleisel** [lemire/simdjson#427]
`get_string` returns a `const char *`, is it safe to cast that to a `char *`? It helps me when working with certain APIs that expect a null-terminated C string

**Comment by lemire** [comment]
It returns a pointer to a location on the string buffer. If you keep the length the same (in bytes), you can probably mutate safely, but not if you change the length.

Otherwise, just copy the string.

**Comment by lemire** [comment]
I am going to close this.
