### ISSUE TITLE
Discussion regarding major refactoring to decouple the tape production and index consumption from parsing (comments eagerly invited)

### ISSUE THREAD

**Issue by lemire** [lemire/simdjson#439]
We are currently somewhat stuck with respect to how we might support efficiently large files
(issues https://github.com/lemire/simdjson/issues/393 https://github.com/lemire/simdjson/issues/171 https://github.com/lemire/simdjson/issues/177 https://github.com/lemire/simdjson/issues/128 and others). I feel that it is currently blocking (psychologically) a move to a wider tape (https://github.com/lemire/simdjson/issues/428) because I am scared of the unforeseen (and costly) consequences.

There are non-trivial issues with respect to memory usage when the files get large. Ideally, you'd want to have small stage 1, building cache-fitting indexes and work from there. But it is hard when our stage 2 is a monolith (hard to change without significant performance penalties).

Instead of working harder, maybe we should be working "smarter" and simply move to more flexible code.

Furthermore, if you have very large files, you probably do not want to materialize "our" kind of DOM (a tape). It is more likely that you will be want to eat up the data into your own favorite data structure. 

The issue has to do with how tightly integrated everything in our code is. So it is not easy or even possible to handle files of different size differently. The tape production should be just one possible output.

We should allow and encourage users to provide their own consumer.

A consumer would have to implement methods such as these ones...

```C
// return true if you want to continue, false to stop
bool found_double(double d);
bool found_int64(int64_t d);
bool found_uint64(uint64_t d);
bool found_start_object();
bool found_end_object();
bool found_start_array();
bool found_end_array();
bool found_true();
bool found_false();
bool found_null();
void found_end_of_document();
void found_error(int error_code);
// gives me a pointer to an available buffer where I could write the string
bool found_start_string(char ** bufferptr);
// I wrote a string of length "len" on the string buffer
bool found_end_string(size_t len);
```

So the `structural_parser` that John (@jkeiser) wrote and that currently handles what we call stage 2 would become a template... where every instance of `write_tape`(and similar functions) would become a call to the generic consumer. So we would *separate* the production of the tape from stage 2. If done right, with a template and proper inlining (`really_inline`), there should be no performance penalty over our current code.

So the 8-byte tape we have right now would become our first "consumer".

Regarding the wider tape (https://github.com/lemire/simdjson/issues/428): it makes it a much safer choice. Indeed, we could keep the 8-byte tape and construct a new consumer that would be a 16-byte tape.

Regarding UTF-8 validation, I would give the user a choice (as a compile-time templated parameter) to do it as part of stage 1. If the user does not want to do UTF-8 validation in stage 1, then they become responsible for doing it in their consumer. In practice, the consumer could write to a string buffer, and then validate this string buffer once. We could make it easy with a clean API for the users to do this work.

We also make it a bit easier to add support for fancy features like large integers (https://github.com/lemire/simdjson/issues/167, https://github.com/lemire/simdjson/issues/425). The consumer can have options... we could have a "bool supports_bigint() const" functions that activates only if bigint are needed. This makes it possible to add features without necessarily having to include it into our tape (and default consumers).

By itself, this does not solve the "large document" problems. However, it modularize the problem and gives us a fighting chance. E.g., currently, the only way we could support >4GB documents is by changing the tape structure. This makes it a daunting task. Now we could say that we have consumers that work only regular JSON documents, and have special consumers that scale better.

But how can we ever crack the large document problem? I think that the bulk of the problem resides in this one function that John  (@jkeiser) wrote...

```C++
char advance_char() {
    idx = pj.structural_indexes[i++];
    c = buf[idx];
    return c;
  }
```

For the most part, `structural_parser` only needs `c` and ` idx` as well as access to `buf`. But exactly how `advance_char()` does it work, the rest of the code does not need to care.

This means that `structural_parser` could take another templated parameter that would provide this function `char advance_char()` and little else. This means, in particular, that if I want to do stage 1 into chunks, I could... 

```C++
char advance_char() {
    if(i >= pj.n_structural_indexes) { // if I am running out of indexes
      refresh(); // call stage 1 over a new block of data, somehow
      i = 0;
    } 
    idx = pj.structural_indexes[i++];
    c = buf[idx];
    return c;
  }
```

Furthermore, currently `pj.structural_indexes` is a 32-bit array, which limits us to 4GB documents, but, obvious, if `advance_char` can be replaced, then we can have a "large file" provider of some kind.

Comments and pull requests invited.

**Comment by DBJDBJ** [comment]
Do we/you have some better idea than an educated guess about the audience? I.e. how many people are having multi-gigabyte JSON files?

Another puzzle is where those multi-gigabyte JSON files are coming from? Because these days there are numerous little JSON formatted https messages coming in and out of server-side.

I just can't imagine use-cases involving multi-gigabyte JSON files?

**Comment by lemire** [comment]
The wikipedia dumps are gigabytes of JSON. Bio-informatics (gene sequencing) is often made of gigabytes of JSON.

My current plan/proposal is that the next release would not support such large files, but it would come later. It would be made possible. Currently, it is just flat out not possible.

**Comment by DBJDBJ** [comment]
## Data vs Structure balance

- The more you move towards the Structure the more sense JSON makes
- The more you move towards the Data the less sense JSON makes

Back to reality. @lemire , I might think the limit of 1 GB might make a lot of sense?

**Comment by lemire** [comment]
> I might think the limit of 1 GB might make a lot of sense? 

Currently, the performance of our design is limited for large files. At 100 MB, we are limited by memory accesses. You can throw 1GB file at simdjson, but you are not going to be reaching 2GB/s or even 1GB/s, while the same content in small chunks (10kB) would be fine.

It is hard for the same code to offer optimal performance for all sizes of file so I think we need more flexibility.

**Comment by jkeiser** [comment]
To ask the "dumb question": what happens if we just change it to 64-bit indices? Does it get a little slower or a lot? I would have thought this scenario was exactly what CPU precaching tries to help us with--loading memory sequentially in a loop. Or is the limitation on the write side?

> It is hard for the same code to offer optimal performance for all sizes of file so I think we need more flexibility.

Note that templates might actually be the right feature here: compile a version of the parser for uint64_t, and branch to the uint64_t version when a file is > 4GB.

**Comment by lemire** [comment]
> Note that templates might actually be the right feature here: compile a version of the parser for uint64_t, and branch to the uint64_t version when a file is > 4GB.

Something like that, yes.

**Comment by lemire** [comment]
>  I would have thought this scenario was exactly what CPU precaching tries to help us with--loading memory sequentially in a loop. Or is the limitation on the write side?

Ok. So the maximal number of structural elements is N when the document contains N bytes. If `structural_indexes` is a 64-bit array, then you need 8*N bytes   just for `structural_indexes` to parse an N byte document. So to parse a 4 GB document, you need to allocate 32 GB *just* for `structural_indexes`. And a 16-byte tape... and you need another 64 GB. And that's just for a 4 GB document.

I don't know about you but I would use some other way to handle a 4 GB document... right?

I am *not* advocating that we write this code to do crazy things like parse 4 GB per se. I am advocating that we open the door.

**Comment by jkeiser** [comment]
Oh, so the concern is more around a ridiculous preallocation. Even in 32-bit documents, that's probably excessive allocation. You'd probably want to allocate a more reasonable # of structural indices, and stop and reallocate if you run out of structurals / etc. The concern being that branch might slow things down a nontrivial amount.

**Comment by lemire** [comment]
> Oh, so the concern is more around a ridiculous preallocation. Even in 32-bit documents, that's probably excessive allocation. You'd probably want to allocate a more reasonable # of structural indices, and stop and reallocate if you run out of structurals / etc. The concern being that branch might slow things down a nontrivial amount.

This allocation is going to set you back in a major way for large files.

I don't think that the real solution is to do dynamic allocation. The real solution is to do stage 1 over small windows that fit in cache. Then do stage 2. The come back to stage 1 once you have run out of indexes. Then do stage 2.

This should be at least as fast as what we are doing now, if the files are large enough... minus a tiny bit of overhead of the order of one instruction per structural element. We are currently in the 40 to 60 instructions per structural element so +1 there is not going to set us back by more than 2% if everything else stays the same. And it may even be free.

*But* I don't know how to do it right now... and I don't think I want us to sacrifice the current code. I just want to open the possibility of doing it in the future.

**Comment by jkeiser** [comment]
Makes sense to me.

**Comment by jkeiser** [comment]
Is this what you mean when you talk about optimizing away page walking?

**Comment by lemire** [comment]
> Is this what you mean when you talk about optimizing away page walking?

Right.

**Comment by lemire** [comment]
[On some systems, memory allocation runs far slower than we can parse (e.g., 1.4GB/s),](https://lemire.me/blog/2020/01/14/how-fast-can-you-allocate-a-large-block-of-memory-in-c/) so the only way to reach speeds in the multi-gigabytes per second range is to avoid having to allocate so much memory.

**Comment by lemire** [comment]
If you cannot reuse pre-allocated memory buffers, then you should, somehow, avoid the memory allocation entirely. E.g., you should avoid materializing your document on a tape... because it is going to cost you...

**Comment by DBJDBJ** [comment]
I am assuming you are aware of [BSON and MongoDB](https://www.compose.com/articles/from-json-to-bson-and-back/)? 

Interesting read.

"... The length itself is encoded as a 32 bit integer giving a notional 4GB capacity, but MongoDB caps the maximum document size at 16MB to avoid giant documents swamping memory...."

**Comment by lemire** [comment]
Optionally, we could offer the consumer to track the indexes in the original string... This could come for free for consumers who do not care.

And given that number parsing is such a high cost, it might be feasible to skip their parsing, or even skip the parsing of some strings. Of course, in such a case, we no longer validate the document per se, but that might be fine.

https://github.com/lemire/simdjson/issues/425

**Comment by lemire** [comment]
Also, we may want to facilitate the capture of small strings.

**Comment by jkeiser** [comment]
As an external user interface, a streaming callback like this sounds great! Kind of like SAX. I think if I were a *user* of it, I'd probably want to be able to pass C++ closures, but we could probably make a subclass that takes those in a constructor or something.

I like the idea of having consumer interfaces internally, too, as long as we don't get stuck on them. It's hard to imagine an interface that won't constrain us in some important way at *some* point. For example, an interface like this one, with a bunch of different methods for different structural types forces the calling code to be branchy. This is fine, because stage 2 *is* branchy ... but [what if it wasn't?](https://github.com/lemire/simdjson/issues/468). Interfaces that pass one thing at a time, too, preclude SIMD optimizations that let you process multiple things at once (8 32-bit floats being parsed at the same time?).

As long as we're not attached, and happy to throw the interface away (or generate a new one) for such things, then a consumer interface like this would be great! I think I'd love a consumer interface for stage 1 that got notified for each structural, so we could experiment with different ways of passing information to stage 2. And having a stage 2 consumer interface like what you suggest would help with tape experimentation too, so +1 there!

**Comment by lemire** [comment]
>  I think if I were a user of it, I'd probably want to be able to pass C++ closures

If you have proposals regarding the API... I am opening the floor!!!

> It's hard to imagine an interface that won't constrain us in some important way at some point

Yeah. But we are deep in a hole as it is, so I suspect we can only *gain* flexibility.

>  Interfaces that pass one thing at a time, too, preclude SIMD optimizations that let you process multiple things at once (8 32-bit floats being parsed at the same time?).

Yes.

> And having a stage 2 consumer interface like what you suggest would help with tape experimentation too, so +1 there!

I agree that it is not going to be perfect, or even ideal, but if it frees us to experiment more, then it is a win.

**Comment by lemire** [comment]
Resolved by @jkeiser  via https://github.com/lemire/simdjson/pull/477
