### ISSUE TITLE
nodejs or/and webassembly binary ?

### ISSUE THREAD

**Issue by parweb** [lemire/simdjson#44]
Is it plan to export as nodejs or/and webassembly binary ?

**Comment by lemire** [comment]
Yes. WebAssembly is probably out for the time being, but a native node extension is something that ought to be done.

**Comment by serv** [comment]
Say we have a working Node binding to simdjson.

In the readme, it reads:

`Performance is optimized for JSON documents spanning at least a few kilobytes up to many megabytes: the performance issues with having to parse many tiny JSON documents or one truly enormous JSON document are different.`

Does this mean that, this library would not be a suitable replacement for `JSON.parse(jsonstring)` in Node.js, where jsonstring is just a single line of JSON string?

**Comment by revskill10** [comment]
The issue is not resolved yet, why close then ?

**Comment by lemire** [comment]
> Does this mean that, this library would not be a suitable replacement for `JSON.parse(jsonstring)` in Node.js, where jsonstring is just a single line of JSON string?

If you are parsing a single line of JSON, then it is unlikely that the time spent parsing is significant enough to warrant optimization *unless* you are parsing many, many such cases. And at that point, things like function call overhead and memory allocations are likely to dominate your running time. This is potentially interesting, but it is not something that this library was optimized for.

**Comment by kevyworks** [comment]
In what size of json file we can expect the benefit? if that is known I think it will use it instead? but for me, as it is working best as a compiled binary..maybe a node script that Interface it using child_process is more suitable?

**Comment by parweb** [comment]
https://github.com/reactjs/rfcs/pull/68#issuecomment-466628049

**Comment by parweb** [comment]
const [isOnline, setIsOnline] = add(users, isOnline(friend.id));

**Comment by lemire** [comment]
> In what size of json file we can expect the benefit?

From the README: "Performance is optimized for JSON documents spanning at least a tens kilobytes up to many megabytes".  This library (simdjson) is for processing large volumes of JSON.

**Comment by lemire** [comment]
My statement above were deliberately pessimistic: simdjson does very well even on tiny documents. At the time I wrote the above comments, I had not benchmarked simdjson on tiny documents.
