### ISSUE TITLE
Missing intrisincs includes?

### ISSUE THREAD

**Issue by llchan** [lemire/simdjson#444]
I'm not sure if I'm doing something non-standard when compiling clickhouse, but I seem to be hitting some missing intrinsics includes when compiling simdjson.  It seems that some source files expect `__m256i` to be declared after `include/simdjson/portability.h` is included, but I only see a `_MSC_VER` piece there.

Do we need something like this?
```diff
diff --git a/include/simdjson/portability.h b/include/simdjson/portability.h
index 12f1eaf..253e909 100644
--- a/include/simdjson/portability.h
+++ b/include/simdjson/portability.h
@@ -65,6 +65,13 @@

 #ifdef _MSC_VER
 #include <intrin.h> // visual studio
+#elif defined(__AVX2__)
+#ifdef IS_ARM64
+#include <arm_neon.h>
+#endif
+#ifdef IS_X86_64
+#include <x86intrin.h>
+#endif
 #endif
```
Or am I misreading this and these are declared elsewhere?

**Comment by llchan** [comment]
Actually, seems that the above patch is not sufficient.  There's also some stuff with the arch-specific namespaces that needs to be ironed out.  Perhaps there's a mechanism here that I'm not familiar with, but how is it supposed to know to use e.g. `simdjson::haswell::add_overflow` to provide `add_overflow`?

**Comment by lemire** [comment]
There are three supported ways to build the code: the single-header version (recommended for users), the CMake build and the Makefile (recommended only for core developers). How you building the code?

Note that we have extensive CI tests. The code builds. In-between releases, there may be various issues, but the build is not broken right now.

**Comment by llchan** [comment]
I'm seeing build issues as part of a cmake-based clickhouse build. Now that I check over there it looks like they forked off their own [CMakeLists.txt](https://github.com/ClickHouse/ClickHouse/blob/master/contrib/simdjson-cmake/CMakeLists.txt), so maybe this is purely a problem with their packaging.

Just for my own education though, how is this expected to work? I'm having trouble understanding how it's supposed to get e.g. `__m256i` in `jsonminifier.cpp`.  Is there some flag that makes the compiler inject an include?

**Comment by llchan** [comment]
Actually, I can reproduce directly in the simdjson repo.  If avx2 is enabled (e.g. via `-march=haswell`) it does not compile.  I tried both the singleheader method as well as the cmake method (both work if I set `-march=westmere`.

**Comment by lemire** [comment]
We use runtime dispatch. We check, at runtime, whether AVX2 is available. Compiling for haswell is likely to break runtime dispatch. Please do not do this.

**Comment by lemire** [comment]
I am closing this. If you have issues with our supported builds, please indicate which one you followed and describe the error.

**Comment by llchan** [comment]
I must be missing something... if the compiler isnt configured to emit AVX2 instructions, how is the runtime dispatch expected to use them?  Or is runtime dispatch expected to _not_ use AVX2?  As it stands right now, if the singleheader method is used in a TU that needs avx2, it will break.  You can try to repro this by running the singleheader amalgamation demo with an additonal `-march=haswell` flag.

I also glanced at the CI configs and it doesnt seem like there's a `ARCHFLAGS='-march=haswell'` equivalent to the `ARCHFLAGS='-march=nehalem'` tests.  It's possible the CI is only testing non-AVX2 builds.

**Comment by llchan** [comment]
Similarly, maybe in the Makefile we want to compile with the _highest_ instruction set, and have the runtime dispatch drop down to a lower implementation if it's not supported?

**Comment by lemire** [comment]
@llchan 

> if the compiler isnt configured to emit AVX2 instructions, how is the runtime dispatch expected to use them?  

If you compile with -march=haswell, your binary will simply not run on hardware that lacks AVX2. We enable AVX2 in software, not as a compiler switch.

> It's possible the CI is only testing non-AVX2 builds.

No. It is not.


> As it stands right now, if the singleheader method is used in a TU that needs avx2, it will break. You can try to repro this by running the singleheader amalgamation demo with an additonal -march=haswell flag.

The minifier code is currently a work in progress. If you are a library user, please use the latest release.

```
$ git clone git@github.com:lemire/simdjson.git
$ cd simdjson
$ git checkout v0.2.1
$ cd singleheader/
$ c++ -march=haswell -o amalgamation_demo amalgamation_demo.cpp -std=c++17
```


Unless you plan to contribute to simdjson, please do not work from HEAD. Work with a release.

We make no guarantee that the current tip on GitHub will work. We only expect users to work from a release.

**Comment by lemire** [comment]
> maybe in the Makefile we want to compile with the highest instruction set, and have the runtime dispatch drop down to a lower implementation if it's not supported?

No. It works the other way around.

**Comment by llchan** [comment]
Ah okay maybe that's the problem then.  Did not realize that master branch is a work in progress.  FWIW ClickHouse appears to be pointing to a git hash that is not an official release---I'll file an issue over there to have them only use official releases.  They may not be aware that non-releases have no guarantees.

Could you point me to some docs on the type of runtime dispatching youre doing? It seems to be a technique I'm not familiar with---normally I'd expect to ship a binary with the highest capabilities and pare back rather than the other way around.

**Comment by llchan** [comment]
Nevermind, figured it out.  So you _are_ compiling pieces with different compiler flags, it's just tucked inside a macro that defines a compiler pragma rather than compiler flag.  Whew, I'm not going crazy.  Thanks!

**Comment by lemire** [comment]
> Did not realize that master branch is a work in progress. 

My experience is that on most projects, releases get specific tags whereas HEAD on master is where new development goes. You would not pick off the Linux kernel from a regular commit and run that on your company servers. There are releases for a reason: we do extra testing prior to the release.

If you navigate on our project page, you will see that we are working toward release 0.3.

> ClickHouse appears to be pointing to a git hash 

That might be fine. My understanding is that they have carefully assessed simdjson.

> They may not be aware that non-releases have no guarantees.

There are some guarantees, like those of the CI. So we know that the code builds and passes tests over multiple compilers. 

However, I would strongly discourage a user from picking a non-release *unless they have done the work of assessing the code for themselves*. 

The ClickHouse folks are what I would consider "advanced users" so I would trust them with a non-release version. They have dug into the simdjson code.

>  It seems to be a technique I'm not familiar with

We are using tricky techniques, yes.

> you are compiling pieces with different instruction sets

We are.

> it's just tucked inside a macro that defines a compiler pragma/attribute, rather than using a compiler flag

I don't think you can do runtime dispatching with a compiler flag. Not in C++.

**Comment by lemire** [comment]
I am going to add a test for your particular issue with the amal. build so that we catch this sort of build issue earlier in the future.

**Comment by llchan** [comment]
Thanks! Appreciate your work on this, and also taking the time to respond.

Is there anything in the CI that can specify the CPU arch that a test is run with? i.e. do we know that we are testing both with/without AVX2, if it's runtime-dispatched on some cloud hardware?

**Comment by lemire** [comment]
> Is there anything in the CI that can specify the CPU arch that a test is run with? i.e. do we know that we are testing both with/without AVX2, if it's runtime-dispatched on some cloud hardware?

We know that the CI support AVX2 because initially, when we started out, simdjson did not run on non-AVX2 hardware. Support for older architectures was added afterward (version 0.2). In fact, I have been doing AVX2-only work for years, on different projects, and CI testing has been around for quite a long time.

Testing on older (pre-AVX2) x64 requires some consideration. We might have gaps in this respect. It is always tricky to support hardware that you do not have. 

What we would need is something like the Intel emulator so that we can emulate older hardware, but it is not clear that we are allowed to do that as per the Intel license.

So issues with simdjson on older hardware is definitively possible.

**Comment by lemire** [comment]
So... yeah, we do not have CI tests on legacy x64 hardware.

**Comment by llchan** [comment]
Got it.  Not a pressing issue, just maybe something to consider down the road.  Might be sufficient to add a `#ifndef NO_TARGET_HASWELL` thing around the `TARGET_HASWELL` stuff, and include a CI variant that explicitly omits the AVX2 implementation at compile-time.

**Comment by lemire** [comment]
@llchan Pull request invited!

There should be no need for macros, however. It is all at runtime. In fact, the `parse` command (in benchmarks) already take an architecture flag. It is a simple matter of generalizing the design. 

We are pretty much limited by how many smart engineers have time to contribute to this project. 

cc @jkeiser
