### ISSUE TITLE
C++17 is doing alligned new/delete by default

### ISSUE THREAD

**Issue by DBJDBJ** [lemire/simdjson#459]
@lemire  No special aligned mem allocators are necessary anymore.  Please see good and short [text here](https://docs.microsoft.com/en-us/cpp/build/reference/zc-alignednew?view=vs-2019).

I have found trivial [function here](https://www.bfilipek.com/2019/08/newnew-align.html) which I suggest we use :

```cpp
// for MSVC use -- /Zc:alignedNew
bool check_aligned_alloc() 
{
	std::vector<__m256> vec(10);
	vec.push_back(_mm256_set_ps(0.1f, 0.2f, 0.3f, 0.4f, 0.5f, 0.6f, 0.7f, 0.8f));
	return (reinterpret_cast<uintptr_t>(vec.data()) % alignof(__m256) == 0);
}
```
I do not know if gcc and clang, do need some special switches.

**Comment by lemire** [comment]
Indeed, we can pass alignment requirements to the new operator, I think this started in C++14. We could use this technique instead of the C equivalent.

It would probably not bring any tangible benefit: we do the alignment in passing as part of padding.

**Comment by DBJDBJ** [comment]
This is not available in C++14. This is C++17 feature.

https://docs.microsoft.com/en-us/cpp/build/reference/zc-alignednew?view=vs-2019

http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0035r4.html

**Comment by lemire** [comment]
I think that you might be correct, it might be new with C++17, but the syntax you are using is just the old style new.

Again, I don't see any tangible benefit down this path.

**Comment by DBJDBJ** [comment]
That is the point ...  C++17 makes it transparent. No aligned new syntax is required.

But, I agree: not using `simdjson::allocate_padded_buffer` will not bring any noticeable performance improvement ...

**Comment by lemire** [comment]
I don't understand. What is the alignment of p in "char * p = new char[0xFF]"?

**Comment by lemire** [comment]
You can specify the alignment in C++17 in this manner...
"new(std::align_val_t{ 64 }) char[0xFF]".

**Comment by DBJDBJ** [comment]
Apparently you do not have to anymore in C++17. 
The offical mantra is "do not use new/delete in your code. Ditto:
```cpp
// alligned by default
std::unique_ptr<char[]> cptr_ = std::make_auto<char[]>(0xFF) ;
```
[Here is a pretty short and good (MSVC) text, on this subject.](https://docs.microsoft.com/en-us/cpp/build/reference/zc-alignednew?view=vs-2019)

**Comment by lemire** [comment]
> Apparently you do not have to anymore in C++17.

I don't understand what you mean. How can it align against custom memory boundaries if you don't tell it how you want the memory to be aligned?

Are you saying that if you write

```C++
char * b = new char[1000];
```
then it is equivalent to...
```C++
char * b = new(std::align_val_t{ 128 }) char[1000];
```

? How could it be? How would the "new" operator know that I want a 128-byte alignment if I don't specify it?


Now, again, yes, we could replace our C code to do aligned assignments by the aligned C++ new/delete, but there is almost surely no benefit.

**Comment by DBJDBJ** [comment]
That is exactly what C++17 compiler does. Please look behind those two links I posted above.

But as I saidI do not see proper new being always called?

**Comment by DBJDBJ** [comment]
Please [see it here](https://wandbox.org/permlink/LRb9Pifb17GONtPA).

Yes, I have benchmarked, and yes there is no benefit to replace simdjson C code that does aligned allocation.

**Comment by lemire** [comment]
In your example, you show how one can declare a type with an alignment requirement, but we have been discussing allocating "char" with "new[]".

**Comment by lemire** [comment]
I am going to close this. Introducing new C++17 features into simdjson is not a goal. In fact, I would prefer if we made as little use as possible of non-C++11 features.

**Comment by DBJDBJ** [comment]
> I am going to close this. Introducing new C++17 features into simdjson is not a goal. In fact, I would prefer if we made as little use as possible of non-C++11 features.

@lemire -- now you want "as little use as possible of non-C++11 features." -- it seems you keep on "moving the goalposts" ... project is moving along and all the things can not be documented in advance ... it is only now we the contributors need to know **before** we start contributing what do you exactly mean by that  ...

This is not mine example it is MSVC Docs example I made to work on the Wandbox.
And, I have done benchmarking which has shown there are no obvious speed increases using naked C++17 new/delete vs what is already in simdjson that is performant and understood.

**Comment by lemire** [comment]
Trying to support C++11 is an issue we need help with: https://github.com/lemire/simdjson/issues/307



We require C++17 but I don’t think we ever wrote that we wanted to switch as much as possible to C++17. It would be in contradiction to issue 307.

But you are correct that these expectations need to be documented so I wrote a CONTRIBUTING file. I hope it helps. I will try to elaborate further.
