### ISSUE TITLE
JsonStream::json_parse return Empty Single Message

### ISSUE THREAD

**Issue by jmackt** [lemire/simdjson#467]
Here is a simple example of the behavior in question:
`
    #include <iostream>
    #include "simdjson.h"
    #include "simdjson.cpp"

    static void parse_json_message(char const* message, std::size_t len)
    {
        simdjson::ParsedJson pj;
        if (!pj.allocate_capacity(512)) {
            std::cerr << "Failed to allocated memory for simdjson::ParsedJson" << std::endl;
            return;
        }
        int res;
        int i = 0;
        simdjson::JsonStream js(message, len, pj.byte_capacity);
        do  {
            res = js.json_parse(pj);
            std::cout << "parsing message " << i++ << std::endl;
        } while ((simdjson::SUCCESS_AND_HAS_MORE == res));

        if (simdjson::SUCCESS != res) {
            std::cerr << "Failed with simdjson error={}" << simdjson::error_message(res) << std::endl;
        }
    }

    int main(int argc, char *argv[]) {
        char const single_message[] = R"exp({"error":[],"result":{"token":"xxx"}})exp";
        char const two_messages[] = R"exp({"error":[],"result":{"token":"xxx"}}{"error":[],"result":{"token":"xxx"}})exp";

        parse_json_message(single_message, sizeof(single_message) - 1);
        parse_json_message(two_messages, sizeof(two_messages) - 1);
        return EXIT_SUCCESS;
    }
`
This behavior is inconsistent with simdjson::json_parse, so I believe it is a bug. 

Thank you,

Joe

**Comment by lemire** [comment]
I am not reproducing your "single empty message" error per se, but your code certainly illustrates a bug.

I have turned your code into a new test, and I have written a potential fix:
https://github.com/lemire/simdjson/pull/469

For the look of it, It is quite simple, really. Hopefully, this will solve the issue.

Thanks for reporting it.

**Comment by jmackt** [comment]
Thank you Daniel, that did the trick for me!

**Comment by lemire** [comment]
There will be a small change to the API: we will take a reference to a padded_string, to make sure that users padded their input strings.

**Comment by lemire** [comment]
Fixed.

**Comment by jmackt** [comment]
> There will be a small change to the API: we will take a reference to a padded_string, to make sure that users padded their input strings.

This is a rather unfortunate and expensive change.  Now it will be required to copy (and sometimes shift) bytes, instead of parsing insitu.  Although I am just one perspective, I think it is generally not the desired behavior when using a streaming parser.

**Comment by lemire** [comment]
> This is a rather unfortunate and expensive change. 

This is not a functional change, it was always required, it was just undocumented.

In simdjson, you need to be able to read 32 bytes beyond the end of the strings.

> Now it will be required to copy (and sometimes shift) bytes, instead of parsing insitu. Although I am just one perspective, I think it is generally not the desired behavior when using a streaming parser.

No. A copy should not be necessary. You just store your JSON data in the padded_string to begin with.
