### ISSUE TITLE
do away with find_the_best_supported_implementation

### ISSUE THREAD

**Issue by lemire** [lemire/simdjson#471]
Currently JsonStream contains a function called find_the_best_supported_implementation. This function should not exist. Do away with it.

**Comment by jkeiser** [comment]
Even further, we should formalize the way you select architectures. By default, it should pick the best implementation under the covers, but as a user of the library you should be able to:

- find out what simdjson feels the best supported implementation is, so you can make decisions based on that information
- specify an alternate implementation if you're super keen on it or feel simdjson isn't doing it right.

**Comment by lemire** [comment]
Right. I marked the issue as "help wanted" as this is something that someone could tackle without having to dig deep into the library.

**Comment by lemire** [comment]
I should point out that runtime dispatching has to be concurrent if you are setting global constants.

**Comment by DBJDBJ** [comment]
```cpp
namespace simdjson {
   struct global_constants final {
     friend struct global_constants_setter ;
    // API
   // 1. resilient in presence of multiple threads
   // 2. non throwing, it can be called any time before or after main()
   // 3. for speed it has to get particular constant in a lazy manner -- not before it is asked for
   // 4. might return encapsulations of implementations (aka algorithms) 
   //    pre-selected for the CPU & architecture found
  }; // global_constants final
}
```

**Comment by jkeiser** [comment]
This was removed [here](https://github.com/lemire/simdjson/pull/501).
