### ISSUE TITLE
> There will be a small change to the API: we will take a reference to a padded_string, to make sure that users padded their input strings.

### ISSUE THREAD

**Issue by jmackt** [lemire/simdjson#472]
> There will be a small change to the API: we will take a reference to a padded_string, to make sure that users padded their input strings.

This is a rather unfortunate and expensive change.  If I understand the interface change correctly, JsonStream parser can no longer parse insitu, but requires a byte copy.  Although I am just one perspective, I think it is generally not the desired behavior when using a streaming parser.

I understand ultimately parsed data is getting written to the tape, just think requiring a padded_string json_parse method is an unnecessary copy.

_Originally posted by @jmackt in https://github.com/lemire/simdjson/issues/467#issuecomment-580037498_

**Comment by lemire** [comment]
Let me recopy my answer here as well.

> This is a rather unfortunate and expensive change. 

This is not a functional change, it was always required, it was just undocumented.

In simdjson, you need to be able to read 32 bytes beyond the end of the strings.

> Now it will be required to copy (and sometimes shift) bytes, instead of parsing insitu. Although I am just one perspective, I think it is generally not the desired behavior when using a streaming parser.

No. A copy should not be necessary. You just store your JSON data in the padded_string to begin with.

**Comment by jmackt** [comment]
Thank you Daniel, sorry for the double posting, I didn't realize the 32 byte padded requirement.  it is unfortunately not possible to write into the padded_string without making a copy, since the data is coming from a network buffer.  Is there any mutation to the memory beyond the message, or is the requirement that the memory is valid?

**Comment by lemire** [comment]
>  I didn't realize the 32 byte padded requirement.

Yeah. It should have been well documented. It was a hidden bug.

It is not going to show up as a bug, unless you cross a page or use a memory validator (like valgrind).

> it is unfortunately not possible to write into the padded_string without making a copy, since the data is coming from a network buffer.

We can rather easily modify the API so that you can provide your own object with your own memory. This could be done with a template, for example.

> Is there any mutation to the memory beyond the message, or is the requirement that the memory is valid?

The input buffer is read-only, so there is never any mutation.

**Comment by jmackt** [comment]
> We can rather easily modify the API so that you can provide your own object with your own memory. This could be done with a template, for example.

That would be perfect!  

Thank you so much for simdjson and your thoughtful response.

**Comment by lemire** [comment]
There you go, it is now a template and you should be able to do what you need.
