### ISSUE TITLE
Class/struct capitalization: ParsedJson or padded_string?

### ISSUE THREAD

**Issue by jkeiser** [lemire/simdjson#476]
I struggle with how to capitalize new structs and classes; I see both `ParsedJson` and `padded_string`.

I don't spend enough time in C++ or any one language, so I tend to copy whatever naming convention the standard library uses--in this case snake_case--but C++ doesn't seem to have an accepted culture, so I'll go with whatever y'all prefer. If asked, my preference is for PascalCase simply because it makes the code less of an "underscore soup," but I'm really not partial.

**Comment by ioioioio** [comment]
See pr #238 . When I did this, all structs were snake_case and somewhat POD, except for ParsedJson and Iterator that were more object oriented. That's how I've tried to make sense out of it without changing everything.

**Comment by lemire** [comment]
We don't have a style guide. We should have a consistent style and ideally some way to check that commits abide by style conventions. Alas I never found a satisfying way to automate such a process in C++, without just forcing a specific formatting. That is, I don't know how to set a few basic rules and then have a check of these rules, without actually having to forcefully reformat (e.g., as with clang-format). It is doable in Java.

I want to avoid/discourage bike-shedding. One can spend a lot of time debating how to format the code... but as long as it is readable, what matters is the compiler output.

Please let us not get into epic discussions regarding style. It can be wasteful.

**Comment by jkeiser** [comment]
## Let's snake_case_all_the_things

@lemire yeah, I don't want to spend much time on this, just want us to pick something :) Consistency is all I really want--not have to spend time thinking about it when I make a new thing.

I usually solve this by stealing the "prevailing style" for the language, but there is huge variation in the ecosystem. The top 3 results for "c++ json library" for me use [snake_case](https://github.com/nlohmann/json#examples), a [PascalCase/camelCase combo](http://open-source-parsers.github.io/jsoncpp-docs/doxygen/index.html), and [PascalCase](https://rapidjson.org/).

Given all that, I suggest we go with the the top one (JSON for modern C++), which accords with C++ stdlib naming, even though it's not my personal favorite: snake_case_all_the_things.

That would mean renaming ParsedJson -> parsed_json, among other things, but we're already mostly snake_cased, so it's not going to be hugely disruptive. That cool?

**Comment by jkeiser** [comment]
Note: by "all the things," I mean classes, structs, methods, variables and functions. UPPERCASE_CONSTANT_OR_MACRO is pretty consistent in our code and we should keep it.

**Comment by lemire** [comment]
That would be fine by me.

**Comment by lemire** [comment]
Macros should stay upper case, it is pretty standard.

**Comment by jkeiser** [comment]
Closing this, I have my guidance, thanks!

**Comment by lemire** [comment]
@jkeiser Do not hesitate to hack the CONTRIBUTING.md file. As @DBJDBJ  remarked, it is unfair to have unwritten rules.

**Comment by DBJDBJ** [comment]
@lemire @jkeiser 

Of course, there will be always styling warriors fighting to the bitter end ...  But, in C++ universe that discussion is settled approx 10 years ago. std lib style is The Style. 
```cpp
namespace  simdjson::yes_this_is_ok_too {
    struct supported_naming_style final {
       // there is set of "required" nested types too
        using value_type  = whatever_works ;
        using type  = supported_naming_style ;
   } ;
} 
  //  this is very often seen
  using ssns =   simdjson::yes_this_is_ok_too::supported_naming_style ;
  // 
 template<typename json_char_type > 
  using json_sview = std::basic_string_view< json_char_type > ;

// and so on ...
```
The benefit of simdjson API "must" also be malleability when using it with other libraries and inside end users app's.

**Comment by lemire** [comment]
@DBJDBJ Thanks. So it is settled.
