### ISSUE TITLE
Public jsonstream.h requires non-exposed src/jsoncharutils.h

### ISSUE THREAD

**Issue by jkeiser** [lemire/simdjson#478]
`include/jsonstream.h` [requires jsoncharutils.h from `src/`](https://github.com/lemire/simdjson/blob/master/include/simdjson/jsonstream.h#L13), which is supposed to be implementation-only. We should either move the calling function to src/jsonstream.cpp, or move jsoncharutils.h (or part of it) into `include`.

**Comment by lemire** [comment]
@jkeiser Agreed. This came about because I made JsonStream a template, and it is most convenient to define a template in the header file... whereas it used to be a regular class.

**Comment by jkeiser** [comment]
This was fixed by #532.
