### ISSUE TITLE
JsonParser: move parse buffers out of ParsedJson

### ISSUE THREAD

**Issue by jkeiser** [lemire/simdjson#479]
We should move the parser's internal buffers to a separate, user-visible `JsonParser` object, which the user can manage separately from the `ParsedJson` output.

This is a **breaking change** (see note at the bottom).

## ParsedJson Today

Presently, `ParsedJson` contains both the parse buffers needed to parse *internally*, and the output buffers for the final result. It is super easy to use (just one object to create and manage). However, this means that you need to finish using the parsed document before you can parse another.

This pattern works reasonably well for server usage patterns where you read one request JSON, use it, and don't read another till you're done with the request. There are no real drawbacks because you want to keep both the internal and output buffers around even after you're done with it (to keep it hot for the next request).

However, it means that the buffers are not independent (you can't have a JSON output without also having a hot parse buffer, and vice versa). This makes it less suited for other uses:

* One-shot JSON: programs that load JSON at the beginning, like for configuration, and keep the JSON output around. These programs will not reuse the parse buffers, but have to keep them around.
* Cached JSON: programs that read a number of JSON files and keep the output in a long-lived structure for the life of the program, looking them up. These programs need to be able to reuse the parse buffers while parsing, but keep the outputs (not destroy them on the next parse).

This also makes experiments with different parsers a little harder to make, since you have to make a whole new ParsedJson if you want to change the buffers you are using.

## Proposal

We create a new JsonParser class, which is architecture-independent and can be instantiated by the user (and destroyed by the user). Users will interact with the system with something like this:

```c++
JsonParser parser(max(len, len2));
ParsedJson doc(len);
parser.parse(buf, len, doc);
parser.parse(buf2, len2, doc); // this overwrites doc but is perfectly legal
ParsedJson doc3(len3);
parser.parse(buf3, len3, doc3); // doc continues to be valid
```

### JsonParser

JsonParser will have the following public interface:

```c++
class JsonParser {
public:
  JsonParser(size_t max_len=DEFAULT_MAX_LEN, size_t max_depth=DEFAULT_MAX_DEPTH);
  size_t max_len(); // max document size we can parse
  size_t max_depth(); // max object/array depth we can parse
  bool ensure_max_len(size_t max_len);
  bool ensure_max_depth(size_t max_depth);
  bool parse(const uint8_t *buf, size_t len, ParsedJson &out);
}
```

And has the following members (copied from ParsedJson):

```c++
class JsonParser {
  size_t depth_capacity{0};
  size_t tape_capacity{0};

  uint32_t current_loc{0};
  uint32_t n_structural_indexes{0}
  std::unique_ptr<uint32_t[]> structural_indexes;; // tape_capacity
#ifdef SIMDJSON_USE_COMPUTED_GOTO
  std::unique_ptr<void*[]> ret_address; // depth_capacity
#else
  std::unique_ptr<char[]> ret_address; // depth_capacity
#endif
  uint8_t *current_string_buf_loc;
}
```

### ParsedJson

ParsedJson, on the other hand, will have `current_loc`, `n_structural_indexes`, `structural_indexes`, `ret_address` and `current_string_buf_loc` *removed*. It will maintain a separate max byte_capacity and depth_capacity, which will be checked for compatibility at the beginning of `JsonParser.parse()`.

This is technically a breaking change to users relying on these fields, but as they are not used in the iterator (* last I checked) and are only really for the parser, it shouldn't matter.

### json_parse() Breaking Change

If we keep the existing [json_parse functions](https://github.com/lemire/simdjson/blob/master/include/simdjson/jsonparser.h#L72) that only take a `ParsedJson`, we'd have to allocate new parse buffers each time. This would make existing code *less efficient than before.* That is not expected for this library, therefore we need to tell those users they have a problem and how to fix it:

* Add `JsonParser` parameter to the end of all `json_parse` functions
* Emit a deprecation error / warning for users if they attempt to call the old one. Not sure how this is done in C++, but probably doable. This should give them the link or advice on exactly what to do to fix it. (NOTE: the error message they get if we don't do this might be good enough: they'll realize they need a `JsonParser` object and go looking.
* Document how to fix the issue in deprecated.md and include a link from top level README.md

## Concern

One thing this proposal doesn't address is having different parse buffers (different JsonParser objects) for different architectures, which might well be something we want to do. I figure we cross that bridge when we come to it, but it bears thinking.

**Comment by jkeiser** [comment]
Thinking about it more, I have an alternate proposal for the user-facing side of this, that handles the same stuff.

I think we shouldn't expose the internal JsonParser or maybe even ParsedJson to the user. Let the user focus in terms of their desired output rather than internal representation. For JSON APIs, this is usually split up like this:

* JsonDocument: a tree-based output optimized for easy lookup.
* JsonIterator: a restartable c++ iterator that scans everything in the document each time.
* JsonCallback (because JsonStream was taken): a callback-based API that doesn't store anything.

Each of these has different parse buffer requirements (JsonDocument needs containing_scope_offset buffer so it can write out object and array skip information).

Here's what I think makes sense:

```c++
JsonIterator::Parser parser();
unique_ptr<JsonIterator> new_iter = parser.parse("file.json"); // Creates a whole new iterator and parses the document.

JsonIterator iter();
parser.parse("file.json", iter);
parser.parse("file.json", iter); // overwrites
```

```c++
JsonDocument::Parser parser();
unique_ptr<JsonDocument> new_doc = parser.parse("file.json"); // Creates a whole new document.

JsonDocument doc();
parser.parse("file.json", doc);
parser.parse("file.json", doc); // overwrites
```

I can imagine a JsonDocument::parse("file.txt") for convenience, but unless you're sure you only want to parse one thing, it's not the recommended usage (it can't keep hot buffers around).

JsonParser will likely still exist, but not be exposed to the user directly. JsonDocument::Parser will contain all buffers necessary to parse and output a JsonDocument.

My last major API design in C++ was a little over a decade ago, so I'm not sure if I have the idioms all right (@dbj?), but with unique_ptr and the ability to allocate on the stack as well, it feels solid.

**Comment by jkeiser** [comment]
The proposal in the previous comment solves the problem of multiple tape formats (though it doesn't solve tape formats with different representations on different architectures). Want to experiment with 64-bit tape? JsonDocument64! (Or `JsonDocument<uint64_t>`, perhaps.)

**Comment by lemire** [comment]
Related: https://github.com/lemire/simdjson/issues/349

**Comment by lemire** [comment]
Sounds good to me.

I think you properly explained why the current API looks like it does: simplicity.

**Comment by jkeiser** [comment]
@lemire not sure if you saw [my second comment](https://github.com/lemire/simdjson/issues/479#issuecomment-581486697) from this morning--you think going ParsedJson -> JsonDocument and JsonParser -> JsonDocument::Parser is a reasonable direction?

**Comment by lemire** [comment]
Yes. 

Have you checked issue 349...?

**Comment by jkeiser** [comment]
Yep. This is an absolute dup. I'll copy this proposal there and close this one, just so we don't have a bunch of issues sitting around.
