### ISSUE TITLE
Move from Projects to Milestones

### ISSUE THREAD

**Issue by jkeiser** [lemire/simdjson#494]
A lot of projects mark issues with Milestones for a version (0.3, 0.4). This seems like a reasonable way to do it, since we do most planning and discussion in issues.

**Comment by lemire** [comment]
Agreed. I realized that some time ago. Do you the necessary access to enter milestones in the GitHub repo?

**Comment by jkeiser** [comment]
Probably! I'll happily take a stab later.

**Comment by lemire** [comment]
That would be fantastic.

**Comment by jkeiser** [comment]
[Done!](https://github.com/lemire/simdjson/milestones) But I used a query to find all the issues in the project and marked them all 0.3. There are 28 issues in the milestone, and 28 in the project. I think it's dusted.

I haven't deleted the projects yet (though we should). It feels so final :) And I figured I'd give you a chance to look it over.

**Comment by lemire** [comment]
Please delete the projects at your leisure. If you choose not to do so, I will get to it...
