### ISSUE TITLE
Minimal simdjson API from user POV

### ISSUE THREAD

**Issue by jkeiser** [lemire/simdjson#495]
Let's make a stab at the minimal document / parser API we'd like to present to the world at 1.0 (it will change between now and then, but that's why it's a stab :)). Rather than focus on the C++ class or interface, however, I'd love if we could focus on what it looks like to the user. Like, if you were explaining it to someone, what would mostly-compileable examples look like?

[JSON for Modern C++](https://github.com/nlohmann/json) has examples like what I mean (though they don't include 

I'd imagine it answering a few basic questions and scenarios like:

* How do I read a file from disk?
* How do I use this in a server endpoint? (Good place to reuse a parser!)
* How do I consume a series of numbers / objects?
* How do I refer to and consume a particular (maybe nested) object field?

To keep from going crazy on it, try to keep it to your Minimum Viable API--the smallest set of features that gets the job done (whatever job it is you think is most important). For example, I wouldn't try to write out both a SAX and a fully-parsed-JSON-tree API; unless you think we *must* release both before going 1.0, pick the one you'd release with first.

Note: not ruling out the API we already have :)

To kick it off, here's a few of my own hopes and dreams:

## Headers

To include simdjson, do this:

```c++
#include "simdjson.hpp"
using namespace simdjson;
```

NOTE: I've left out instructions for compiling it / bringing in headers because I want to focus on the C++ side of the API.

## Basic Usage

Imagine you have this JSON:

```c++
string json_text = R"(
  [
    { "Name": "John", Legs: 2 },
    { "Name": "Sally", Legs: 2 }
  ]
)";
```

Here's how you parse it, and how you consume and iterate over the JSON values:

```c++
//
// Parse a JSON string
//
json::doc people = json::parse(json_text);

//
// Consume elements and values directly
//
json person = people[1];
string name = person["Name"];
int legs = person.get("Legs", 2);
cout << sally_name << " has " << sally_legs << " legs!" << endl;
// Prints: "Sally has 2 legs!"

//
// Iterate over an array of objects
//
for (auto person : people) {
  cout << person["Name"] << " has " << person.get("Legs", 2) << " legs! ";
}
// Prints: "John has 2 legs! Sally has 2 legs!"
```

## Handling Errors

simdjson does not use exceptions internally, and will parse with the same performance whether you use exceptions or not. However, the simdjson *API* may be used either with or without C++ exceptions. To avoid exceptions (which you should do if you want your calling code to run efficiently), you can unpack and check errors using the valstat pattern:

```c++
//
// Handling errors instead of throwing exceptions
//
auto [people, error] = json::load("people.json");
if (error) { cerr << "Error loading people.json: " << error << endl; return error; }
auto [person, error] = people[1];
if (error) { cerr << "Error getting people[1]: " << error << endl; return error; }
auto [name, error] = person.get<string>("Name");
if (error) { cerr << "Error getting people[1].Name: " << error << endl; return error; }
auto [legs, error] = person.get("Legs", 2);
if (error) { cerr << "Error getting people[1].Legs: " << error << endl; return error; }
cout << "Name: " << name << ", Legs: " << legs << endl;
```

simdjson does not use exceptions internally, and unpacking errors guarantees no exceptions will ever be thrown from C++.

## Reading Files

simdjson also has an API to read files:

```c++
//
// Read a file and write it back out in "minified" form (no whitespace)
//
json doc = json::load("twitter.json");
cout << doc;
```

## Parsing Multiple Documents

If you'll be reading multiple documents, it is much more efficient to keep a single parser around. 

```c++
//
// Parse and minify multiple documents in a loop
//
const string[] filenames = { "twitter.json", "twitter2.json", "twitter3.json" };
json::parser parser;
foreach (string filename : filenames) {
  json::doc &doc = parser.load(filename);
  cout << doc;
}
```

Note the `json &` above: `json::parser` keeps the *document* cached and reuses it each time it parses. Along with keeping the parser's internal buffers, this minimizes costly allocations and speeds things up by keeping buffers in cache.

Note: if you're threading, keep one parser per thread--`document::parser` is *not* thread safe!

## Server Example

Here's a lightweight server endpoint that takes JSON POST requests and minifies them in responses, putting everything here together:

```c++
//
// Use it in a server loop (https://github.com/yhirose/cpp-httplib in this example)
//
json::parser parser;
Server svr;
svr.Post("/minify", [](const Request& req, Response& res) {
    auto [doc, error] = parser.parse(req->body);
    if (error) { res.status = 400; return; }
    res.body = doc;
});
svr.listen("localhost", 1234);
```

## Brief API Notes

* `json::doc` owns the buffers and data for a parsed JSON document.
* `auto [val, error] = ...` is the normal `noexcept` way to explicitly handle an error.
* Navigation and iteration like `[]`, `get()` and `for (auto x : ...)` yield `json` values--references to positions in a doc.
* You can attempt to convert or navigate a result without unpacking the error, and it will throw `invalid_json` at that point if appropriate. This will never happen if you unpack errors.

**Comment by jkeiser** [comment]
A few notes / criticisms I have on the API I wrote above (there are always tradeoffs):

* It requires some form of auto allocation in the parser so that you can just new up a parser and toss documents at it. I think this is not unreasonable: check document size each time a new document is given to parse, and reallocate buffers if needed up to a certain size.
* It does not 
* It comes with the possibility of segfaults if you keep a json reference longer than the document itself. I was unwilling to move to `shared_ptr` for fear of iteration performance; maybe I was wrong about that?
* It doesn't address JsonStream, ndjson, SAX or struct deserialization. I don't see these in the minbar for 1.0, but am willing to be wrong about that :)
* I didn't make it clear, but I think we should make anything not in the user facing API inaccessible or clearly internal, to avoid people taking dependencies on our internal tape representation or parsing strategy.

**Comment by lemire** [comment]
Note that we can always point users to a complete example, or even include it (the complete example) in the documentation.

**Comment by lemire** [comment]
> It comes with the possibility of segfaults if you keep a json reference longer than the document itself.

Surely this can be avoided, right?

**Comment by lemire** [comment]
> to avoid people taking dependencies on our internal tape representation or parsing strategy.

I think that this was a concern from version 0.1. And, actually, the tape structure changed multiple times. We want to be able to keep doing that. Some amount of abstraction is required.

**Comment by lemire** [comment]
> each auto is a declaration, and c++ doesn't like when you declare the same variable (error) multiple times. This puts a damper on my enthusiasm for struct decomposition

Can't you just drop the auto the second time? (Daniel wrote naively.)

**Comment by jkeiser** [comment]
> Note that we can always point users to a complete example, or even include it (the complete example) in the documentation.

Yep, and we should (though we should do both; snippets really help teach). This post is largely about writing what a user will do when they use our API, so that we can get preemptively embarrassed when we make it too hard, and then fix it :)

> > It comes with the possibility of segfaults if you keep a json reference longer than the document itself.
> Surely this can be avoided, right?

The two main strategies off the top of my head are to use `shared_ptr`, which AFAIK introduces a reference count to the document; and to only allow users to navigate via closures so that you can guarantee the object stays around while you invoke the closure. It sort of seems like C++ users are used to being asked to manage lifetimes in their heads, but if I've got that wrong then I suggest we use shared_ptr :)

> > each auto is a declaration, and c++ doesn't like when you declare the same variable (error) multiple times. This puts a damper on my enthusiasm for struct decomposition
> Can't you just drop the auto the second time? (Daniel wrote naively.)

The [structured binding proposal](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0144r0.pdf) @DBJDBJ linked indicates you can't. However, it notes that you can do `tie(x, y) = ...` so perhaps that's fine.

**Comment by DBJDBJ** [comment]
@lemire @jkeiser 

Music to my ears.

> Note that we can always point users to a complete example, or even include it (the complete example) in the documentation.

> Yep, and we should (though we should do both; snippets really help teach). This post is largely about writing what a user will do when they use our API, so that we can get preemptively embarrassed when we make it too hard, and then fix it :)

Guys, I suggest I start the "documentation" branch and in there I start the `~/doc/simdjson_api.md`, and then start from the copy of @jkeiser  text in here.

Then I start a sample(s) inside `~/singleheader` 

Then we can congregate on the API issue in the API branch.

**Comment by jkeiser** [comment]
@DBJDBJ I assume you mean we'd discuss differences here and edit a canonical copy there as we agree on things?

**Comment by jkeiser** [comment]
We've made some changes in the general direction I proposed ... instead of `json::doc` we have `document` at the top level, and we've added a full `active_implementation` `available_implementations` API to control and inspect our runtime architecture-based implementation selection.

Next up for me is navigation APIs, which is probably where we end up with the `json` rename (currently there is no type representing a single element within a file, except perhaps the iterator).

**Comment by jkeiser** [comment]
After writing out some code and examples, here's a navigation API proposal that tracks with what many JSON libraries do. The big difference between it and the current DOM iterator interface is that it lets you iterate arrays and objects with specific types, allowing the user to cast to that and then safely use it.

Here are some examples that read twitter.json, old vs. new. I'm using the exception-based error handling for illustrative purposes, but all calls here will support `auto [error, val] = ...`. One thing I'd *like* is for 

They all start with the preamble to load the document:

```c++
#include "simdjson.hpp"
using namespace simdjson;
json::document document = json::load("twitter.json");
```

### Object field lookup and integer extraction

> ```c++
> // Prints the number of results in twitter.json
> uint64_t result_count = document["search_metadata"]["count"];
> cout << "Results: " << result_count << endl;
> ```

### Array iteration and conditionals (bool extraction)

> ```c++
> // Print verified users.
> json::array statuses = document["statuses"];
> for (json::object tweet in tweets)) {
>   json::object user = tweet["user"];
>   if (user["verified"]) {
>     cout << "Verified user: " << user["screen_name"] << endl;
>   }
> }
> ```

### Object key/value pair iteration

> ```c++
> // Print image names and sizes
> for (json::object tweet in document["status"]) {
>   for (json::object image in json::array(tweet["entities"]["media"])) {
>     cout << "Image: << image["url"] << endl;
>     for (auto [key, value] in json::object(image["sizes"])) {
>       cout << "- " << key << ": " << value["w"] << " by " << value["h"] << endl;
>     }
>   }
> }
> ```

## Notes

* **Optional Keys:** Many times, keys are *optional* and have default values. It'd be nice to be able to say `int count = document["count"].default_to(0)` or something, and have it throw if the wrong *types* are there, but give you 0 if the key is missing. I'm still thinking this through, because I'd also like object lookup chains (e.g. `document["metadata"]["count"].default_to(0)`) to do the same thing when an nonterminal object is missing, and that takes a little care to do right.
* **No Parent Navigation:** Parent navigation is done by the user keeping a reference to the parent on the stack. The previous iterator kept its own stack around for this purpose.
* **No Reverse Iteration:** Not that we don't want to, but it's not well supported by the tape format and it's a little bit of a niche scenario.
* **RAII:** the current design doesn't enforce that the document live longer than the object/array references, if you own the document. We may want to enforce that or use `shared_ptr`, but shared_ptr comes with its own issues.

## Perf

* **Document Pointer Redundancy:** Each object and array requires its own document pointer, and you're likely to have two or three on the stack at any given time. We rely on the compiler recognizing these thin structures, destructuring them, and using a single document pointer. We'll need to check for this before we check in.
* **Slow Object Field Lookup:** Looking up an object field is O(n), where n is the number of key/value pairs in the document. `if (status["favorited"] || status["retweeted"])`, for example, will be super slow because they have to skip through on the order of 20 keys each time (multiplied by the number of tweets). This sucks, and the use of an indexer ("...") gives the user a false sense of performance from it. We may want to remove the nice indexer in favor of a `find_key()` or something that doesn't give that impression, and allow the user to cast to a C++ map if they want to do multiple lookups. It's possible we could cache something in the `object`, too. We should also look into support for this in the tape.
* **Slow Size Check:** Normal arrays and objects have constant time `size()`. Ours have neither. Users will want it, for arrays in particular, so they can new up an array ahead of time. For now, it's just a limitation of the tape that we may want to fix.
* **Slow Array Index:** Same as the above two. You can advance 1 but you

**Comment by jkeiser** [comment]
# ndjson API

The other current API that needs to mesh with everything else is JsonStream. This also needs some thought, but here's a sketch of the user interface:

```c++
// Iteration (primary interface)
for (const json::document& doc : json::stream("[1,2]\n[3,4]\n5\n")) { ... }

// Persistent stream parser
json::parser parser;
for (const json::document &doc : parser.stream("[1,2]\n[3,4]\n5\n")) { ... }

// Explicit iteration
json::stream stream("[1,2]\n[3,4]\n5");
while (stream.has_more()) {
  const json::document &doc = *stream;
  cout << "Doc: " << doc << endl;
  stream++;
}

// Error codes
for (auto [doc_error, doc] : json::stream("[1,2]\n[3,4]\n5")) {
  if (doc_error) { cerr << error_message(doc_error) << endl; exit(1); } // An error will be emitted on the first bad document. Do not continue if you see one.
  ...
}
```

**Comment by lemire** [comment]
@jkeiser  Looks good. I am concerned about fast array indexing as well as fast size checks. I think that the "find_key" may or may not be slow... see our numerous discussions regarding optimizations for short ASCII keys. I have not yet seen JSON documents with very, very numerous keys in a single object so it may not be an actual source of major concern.

**Comment by jkeiser** [comment]
I've created an [API milestone](https://github.com/lemire/simdjson/milestone/5) to track API cleanup for existing functionality. I deliberately didn't include SAX in there, even if that blocks 1.0: this is to tell us when we've cleared the big rocks in our existing API and made it as good as we know how.

@DBJDBJ we probably need something there for the ability to use custom allocators, if it isn't already. I feel like ensuring people can use the existing functionality anywhere (within reason) is a part of designing a clean API.

**Comment by jkeiser** [comment]
Thinking about how a streaming API would affect our DOM API, the biggest change would be the iterators, which could now encounter errors between elements. Given that the Delta is so small, it might be worth making the iteration API capable of yielding errors instead of values, so that we could switch users to streaming backends without changing their usage.

The one place it would really impact people would be object iteration: the `for (auto [key, value] : obj)` syntax might not be possible anymore. Unless inline destructuring supports some kind of casting or partial conversion

**Comment by jkeiser** [comment]
I think the API we have checked in represents the best effort here, we can discuss more on future issues.

**Comment by lemire** [comment]
Agreed.
