### ISSUE TITLE
remove the using namespace std in the header only version

### ISSUE THREAD

**Issue by Edhebi** [lemire/simdjson#50]
`stage1_find_marks.cpp` and `stage2_build_tape.cpp` both starts with a `using namespace std` line. which are agglomerated for the header-only version.

Since the code is not namespaced, they while be visible in the unit including them, wich can be a problem.

easy fix:
```cpp
namespace simdjson
{
#include <simdjson.h>
#include <simdjson.cpp>
}
```

**Comment by lemire** [comment]
Agreed.

**Comment by lemire** [comment]
In a branch about to be merged, we got rid of "using namespace std".
