### ISSUE TITLE
Add compile-time check for C++17 support

### ISSUE THREAD

**Issue by lemire** [lemire/simdjson#502]
Currrently, we require C++17. I do not think we check for C++17 support (e.g., via `__cplusplus`) but we probably should so that users who rely on older compilers get something better than a long list of errors.

cc @DBJDBJ

**Comment by jkeiser** [comment]
I haven't tested it myself, but I think @DBJDBJ is the one who added this check in simdjson.h:

```c++
#if (SIMDJSON_CPLUSPLUS < 201703L)
#error ...
```

**Comment by lemire** [comment]
good point
