### ISSUE TITLE
In old hardware, simdjson appear to report unhelpful error message "uninitialized"

### ISSUE THREAD

**Issue by lemire** [lemire/simdjson#505]
See downstream issue https://github.com/eddelbuettel/rcppsimdjson/issues/7

cc @jkeiser

**Comment by lemire** [comment]
I have updated the title. It appears that the issue is that when the hardware is not supported by simdjson, we fail to give a useful error message. This can be frustrating to the users who need to figure out what the problem might be.

I will label this as a bug.

**Comment by lemire** [comment]
Done. I consider that this is a bug.

Thanks to @eddelbuettel for drawing attention to it.

**Comment by jkeiser** [comment]
So, I actually think this bug is fixed in master: the new error code is reported and the error message.

I think, however, that we should consider this a terminal error and abort (at least by default). This is not a recoverable or temporary error.

**Comment by jkeiser** [comment]
I also like @eddelbuettel's idea of failing to compile on such a machine. It's very common to compile on the machine you plan to run on. It also introduces the possibility of a host only mode that compiles for your architecture specifically, with the appropriate implementation for that architecture.

**Comment by eddelbuettel** [comment]
I added an `#if __cplusplus >= 201703L` test and would luuuv to check for hardware. Can modern compilers not tell us (via the compiler) if AVX-2, AVX-513, ... are available? Isn't there `USE_AVX` and `USE_AVX512` ?

**Comment by jkeiser** [comment]
You might at least be able to remove the if cplusplus check on master--I think [this line](https://github.com/lemire/simdjson/blob/560f0742cc0895d00d78359dbdeb82064a24adb8/include/simdjson/simdjson.h#L16) handles it.

**Comment by eddelbuettel** [comment]
Nice, but I have a different use case. I do a (soft, not-enforced) declaration of a requirement for C++17 but some CRAN machines still attempt a build. At that point I as maintainer do _not_ want a hard error but rather a soft recovery.  See https://github.com/eddelbuettel/rcppsimdjson/issues/6 for a brief discussion.  Apparently the clang being brought to battle is too ancient...

**Comment by lemire** [comment]
I think adding explicit documentation on how to check for an unsupported CPU would go a long way toward closing this issue, see PR

https://github.com/lemire/simdjson/pull/508

**Comment by lemire** [comment]
I am going to close this given that we have better documentation and that the underlying issue appears to be solved. It looks like the downstream issue is fixed as well.
