### ISSUE TITLE
[cmake] add soversion to the resulting shared library

### ISSUE THREAD

**Issue by cdluminate** [lemire/simdjson#52]
Adding a SOVERSION to the resulting shared object would help indicating API/ABI changes in this library. This would greatly benefit linux distribution packagers. Please consider adding the following patch to master:

```patch
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index ea48953..dd7f2a4 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -32,7 +32,8 @@ if(NOT MSVC)
 ## We output the library at the root of the current directory where cmake is invoked
 ## This is handy but Visual Studio will happily ignore us
 set_target_properties(${SIMDJSON_LIB_NAME} PROPERTIES
-  LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR})
+  LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}
+  SOVERSION 0)
 MESSAGE( STATUS "Library output directory (does not apply to Visual Studio): " ${CMAKE_BINARY_DIR})
 endif()
```

**Comment by atomheartother** [comment]
How about adding a LIBRARY_VERSION variable to the CMakeLists? Which version should we start at anyway, `0.0.1`?

**Comment by cdluminate** [comment]
> How about adding a LIBRARY_VERSION variable to the CMakeLists? Which version should we start at anyway, `0.0.1`?

Sounds good to me. Actually any version number will do as long as it indicates ABI/API changes in the library. Generally it's recommended to follow the [semantic versioning](https://semver.org/) convention.

**Comment by lemire** [comment]
Pull request invited.

**Comment by cdluminate** [comment]
I'm afraid this issue has been reintroduced in version 0.4.0

**Comment by lemire** [comment]
@cdluminate I am on it. I expected this issue to be fixed definitively.

**Comment by lemire** [comment]
Ok. So for 0.4.0 we bumped the soversion from 1 to 2.

I don't understand soversion, and why we have to have a version number and soversion number, but we did bump the version number with 0.4.0 release. It has been incremented by one.

If it the rules are more complicated, could you explain them to me so we can resolve this issue for real?

**Comment by lemire** [comment]
Here is the older commit where you bumped it up from 0 to 1:

https://github.com/simdjson/simdjson/commit/5b2f7d33749a6284e0f35188f3d7dd5120f65fb0

And here is the commit where you made it 0:

https://github.com/simdjson/simdjson/pull/98

And here is the commit where I incremented it again for 0.4.0:

https://github.com/simdjson/simdjson/commit/e01f1434fb15218208d98ff6fef93d3a4bad349d

**Comment by lemire** [comment]
At my request, you did document the reason why we use a different soversion than the library version. So we now bump the soversion with every minor version (starting from where you made it... 0, 1, 2...)

**Comment by lemire** [comment]
@cdluminate  Ok. We did bump the soversion, it is just no long applied to the target in the new CMake.

https://github.com/simdjson/simdjson/issues/1014

**Comment by lemire** [comment]
@cdluminate So there was a regression but it is not that we forgot to increase the soversion number, as I thought, it is that we removed the assignment of the version number to the library. So we were changing the version numbers, but without telling CMake to do the right thing with it.

**Comment by cdluminate** [comment]
@lemire The missing cmake code is

```
set_target_properties(<simdjson_shared_library> PROPERTIES
  VERSION $(SIMDJSON_VERSION)
  SOVERSION $(SIMDJSON_SOVERSION)
)
```

**Comment by lemire** [comment]
@cdluminate Can you please come to issue https://github.com/simdjson/simdjson/issues/1014 and to PR https://github.com/simdjson/simdjson/pull/1016
