### ISSUE TITLE
Return error objects wrapping the error code

### ISSUE THREAD

**Issue by jkeiser** [lemire/simdjson#520]
We can still have it just be an int, obviously, so it gets stored in a register; but it'd be nice if you could write:

```c++
auto [doc, error] = document::parse(json);
if (error) {
  printf("%s\n", error.error_message());
  exit(1);
}
```

You could also then offer an operator bool() that treats both SUCCESS and SUCCESS_AND_HAS_MORE as success, allowing JsonStream to use the same nice `if ()` statement.

**Comment by lemire** [comment]
This would improve usability.

**Comment by jkeiser** [comment]
It also occurs to me that the exception object is (at least presently) *precisely the same as* this object. So we'll probably reuse it.

**Comment by jkeiser** [comment]
There is a question of what to name this. `error_code` is not actually taken, it turns out: `ErrorValues` is what that was called in simdjson 0.2. I don't think I'd want to name this `error`. It would be nice to reserve that name for a future where we include file/line #'s.

**Comment by jkeiser** [comment]
Closing this in favor of #538, which makes `cout << error` and `printf("%s", error_message(error))` (without the .c_str()) work.
