### ISSUE TITLE
C# Version

### ISSUE THREAD

**Issue by honorew** [lemire/simdjson#53]
Hi ：Is there a version of C#？thanks.

**Comment by lemire** [comment]
Not currently but given the introduction of SIMD intrinsics in .NET core 3, it is definitively a new future possibility.

https://apisof.net/catalog/System.Runtime.Intrinsics.X86.Avx2

**Comment by honorew** [comment]
it's great.

**Comment by DesWurstes** [comment]
@lemire I was going to ask the same question without a `#`. Since this software favors performance, it would be useful for C programmers if there were a C version. Would you merge if I created a pull request that 1) adds a C version or even simpler 2) separates the C++ part to a different file so that without code duplication it'd be both C and C++ compatible via preprocessor macros?

**Comment by lemire** [comment]
@DesWurstes 

It would be best to open the 'C' question up as a distinct issue. Can you do that?

**Comment by lemire** [comment]
I am reopening this issue regarding C# since it is something we want to track.

**Comment by EgorBo** [comment]
I am trying to port it, already ported `ParsedJson+Iterator` and started `stage1` will submit a PR once I finish 🙂 sounds like a good test for the System.Runtime.Intrinsics API.

**Comment by lemire** [comment]
+1

**Comment by tannergooding** [comment]
I'm definitely happy to be tagged on any PR for the C# effort and to hear any other feedback on the .NET HWIntrinsics.

**Comment by EgorBo** [comment]
finished both `stage1_find_marks` and `stage2_build_tape` the only two missing pieces are `parse_number()` and `parse_string()` - they are quite huge 🙂 but in general the code is C# friendly:
![image](https://user-images.githubusercontent.com/523221/53284354-32337080-3764-11e9-9d8b-23ace5a3b5a7.png)

**Comment by EgorBo** [comment]
Just finished an initial version: https://github.com/EgorBo/SimdJsonSharp
@lemire do you mind if I keep it in my repo (I am planning to clean up and optimize some C# specific things) or you prefer to have it here in this repo in some folder?

**Comment by lemire** [comment]
Speaking for myself: a separate repo is fine but we should link to it.
