### ISSUE TITLE
Add github pages

### ISSUE THREAD

**Issue by jkeiser** [lemire/simdjson#553]
I'm also OK with you publishing it on your own server if you want, but if you don't want the maintenance burden, this would let us get it set up and able to be automatically updated from source, which is convenient for all of us :) Only the repository owner can do this:

https://github.com/lemire/simdjson/settings

Go to the GitHub Pages section and enable it:

![image](https://user-images.githubusercontent.com/654882/76542676-95ad4080-6442-11ea-99a4-575670279f01.png)

I think enabling from master is best: we can customize precisely how it generates pages and where from. I don't care what theme we choose, if any. That's also changeable.

**Comment by lemire** [comment]
Done.
