### ISSUE TITLE
add cmake testing to our circleci setup

### ISSUE THREAD

**Issue by lemire** [lemire/simdjson#56]
We are currently not testing using cmake with circleci...
https://github.com/lemire/simdjson/blob/master/.circleci/config.yml

**Comment by lemire** [comment]
@TkTech : do you know a cheap and efficient way to do that? I know how to do it easily on travis... but not on circleci.

**Comment by TkTech** [comment]
Sure, I can flesh out the circleci tests after work if you'd like a PR.

**Comment by lemire** [comment]
@TkTech That'd be great.

You live in Ottawa?

**Comment by TkTech** [comment]
I do indeed!

**Comment by lemire** [comment]
So we are almost neighbours. (I was in Ottawa all week last week.)

**Comment by TkTech** [comment]
Put up a PR. We should also remove travisci, or at least disable running the tests and explicitly specify an arch that supports AVX2 for building (ex: `-march=haswell`).

Not all travisci hosts support AVX2, so builds will continue to randomly fail when it tries to execute on a machine without it (ex: #60) All circleci v2 hosts are Haswell so AVX2 is available.

Could probably also get rid of drone as well, no reason to have so many ci running, doesn't really offer anything. Need to keep appveyor as it's necessary for Windows builds.

**Comment by lemire** [comment]
@TkTech I removed travis.
