### ISSUE TITLE
Odd warning about freeing through stringview

### ISSUE THREAD

**Issue by geofflangdale** [lemire/simdjson#57]
`In file included from /home/geoff/git/simdjson/include/simdjson/common_defs.h:4:0,
                 from /home/geoff/git/simdjson/benchmark/parse.cpp:33:

In function ‘void aligned_free(void*)’,
    inlined from ‘int main(int, char**)’ at /home/geoff/git/simdjson/benchmark/parse.cpp:262:15:

/home/geoff/git/simdjson/include/simdjson/portability.h:123:9: warning: attempt to free a non-heap object [-Wfree-nonheap-object]
     free(memblock);
     ~~~~^~~~~~~~~~
`
gcc 7.2.0 doesn't like us trying to look through string_view to free our data. I don't understand this warning or what the analysis thinks it's doing.

**Comment by lemire** [comment]
Closing. An upcoming merge will introduce a `padded_string`.
