### ISSUE TITLE
benchmark against rust de facto standard lib: serde

### ISSUE THREAD

**Issue by LifeIsStrange** [lemire/simdjson#62]
https://github.com/serde-rs/json

**Comment by TkTech** [comment]
Probably not a fair benchmark, serde is [relatively] slow when not using structs. Serde benchmark for canada.json is about 1/4 the speed.

**Comment by geofflangdale** [comment]
Feel free, we would be interested to see the results.

**Comment by lemire** [comment]
This was closed? Anyhow: I am encouraging people to do more benchmarking.
