### ISSUE TITLE
Code 

### ISSUE THREAD

**Issue by Olayemi12** [lemire/simdjson#63]
https://github.com/hanxu317317/city_pickers/blob/65478dd09823862607d56ee72d34b8892ddfd2e1/lib/modal/result.dart#L9

**Comment by Olayemi12** [comment]
https://github.com/hanxu317317/city_pickers/blob/65478dd09823862607d56ee72d34b8892ddfd2e1/lib/modal/result.dart#L9

**Comment by geofflangdale** [comment]
I cannot see how this is an issue for us.
