### ISSUE TITLE
Support Unsigned 64-bit integer

### ISSUE THREAD

**Issue by gigoh** [lemire/simdjson#68]
As I know number field in JSON is not limited by the number of digits,
but parser is limited by their own language specification.

In terms of the datatype, uint64 is frequently used for identifier, hash value...
and it is natural that many of Cpp based project uses `unsigned long`.

My opinion is that it would be great if the parser supports both `uint64` and `int64`.

I am really impressed with this artwork. thanks a lot =)

**Comment by lemire** [comment]
That's reasonable and could be added without too much work.

**Comment by lemire** [comment]
Close via https://github.com/lemire/simdjson/pull/306

Credit: @saka1
