### ISSUE TITLE
Two headers have CRLF line terminators

### ISSUE THREAD

**Issue by mr700** [lemire/simdjson#69]
This is a minor... Only two files (singleheader/simdjson.h and include/simdjson/common_defs.h) have CRLF line terminators (DOS).

The first one looks auto generated, so only include/simdjson/common_defs.h is problematic.

**Comment by lemire** [comment]
Let us fix that!

**Comment by lemire** [comment]
Pull request invited.

**Comment by mr700** [comment]
Done, see https://github.com/lemire/simdjson/pull/78

**Comment by lemire** [comment]
Reopened as per this comment: https://github.com/lemire/simdjson/pull/78#issuecomment-467453259

**Comment by mr700** [comment]
No longer relevant, this is fixed in "Daniel Lemire <v0.0.1> First release (0.0.1)
