### ISSUE TITLE
Improve accuracy of get_double 

### ISSUE THREAD

**Issue by EgorBo** [lemire/simdjson#71]
When I parse `-65.619720000000029` value I get '-65.619720000000044' (other parsers return correct value for it)

**Comment by lemire** [comment]
This passes our current accuracy threshold which is set to a relative error of 1e-14.

https://github.com/lemire/simdjson/blob/master/tests/numberparsingcheck.cpp#L82

Let us lower this threshold!

**Comment by lemire** [comment]
(Note that our number parsing code is relatively standard. Except for a vectorized integer parsing that can get called, we don't do anything special.)

**Comment by geofflangdale** [comment]
Our behavior currently tracks (and benchmarks against) systems like RapidJSON in their "fast" mode. Would fixing this require us to change that?

**Comment by EgorBo** [comment]
Oh, thanks for pointing me that piece of code!
I found this value in `canada.json`

**Comment by plokhotnyuk** [comment]
The error is ~1ULP but it should be documented properly if there is no option to parse more precisely.

**Comment by lemire** [comment]
We have an accuracy threshold and that we test for it, with the goal of being inline with something like RapidJSON in fast mode. But the current setup can be improved in many ways:

- Explicitly documented.
- Explicitly compared against other parsers (e.g., RapidJSON).
- The accuracy itself could be improved with minimal loss of performance (as per @plokhotnyuk's comment).

Let us do better!!!

**Comment by lemire** [comment]
I have a PR that should solve this issue. In particular, it does parse "-65.619720000000029" to "-65.619720000000029". Performance on all but the most "number intensive" files is unaffected.

**Comment by lemire** [comment]
Closing.
