### ISSUE TITLE
Make `move_forward()` more useful by not silently consuming scope changes.

### ISSUE THREAD

**Issue by TkTech** [lemire/simdjson#73]
https://github.com/lemire/simdjson/blob/389f8b514e2a6415df481aef2231cceb8f174d46/src/parsedjsoniterator.cpp#L74

`move_forward()` can be used to very easily travel the tree, however it silently consumes the end of scopes (`]` and `}`) which means your consumer needs to check the depth after every return to see if the level has changed.

Instead of looping and consuming all the ends-of-scope before returning, `move_forward()` should handle just one depth change as it does for an increase (`{`) and return immediately. This allows the caller to always know when its both entered and exited a scope without having to also look at the depth, which can change by multiple levels in a single call.

With this change writing a pretty printer becomes a fair bit cleaner. Psuedocode:

```python
indent = 0
while iter.move_forward():
    if iter.get_type() == '{':
       print('{}{{'.format(' ' * indent))
       indent += 1
    elif iter.get_Type() == '}':
        indent -= 1
        print('{}}'.format(' ' * indent)) 
     ...
```

For example this is what currently happens:

```
[ <-- returns True
    { <-- returns True
    ...
    } <-- silently consumed, no return
 ] <-- silently consumed, no return
<-- returns False
```

And this is what would be preferred:

```
[ <-- returns True
    { <-- returns True
    ...
    } <-- returns True
 ] <-- returns True
<-- returns False
```

Would you accept this change?

**Comment by lemire** [comment]
Can you elaborate a tiny bit? (If only so that other people reading this can understand the issue.)

**Comment by TkTech** [comment]
Better?

**Comment by lemire** [comment]
Now it is clear.

> Would you accept this change?

If it makes the API easier to use, yes. Of course.

cc @geofflangdale

**Comment by geofflangdale** [comment]
I think this change makes a lot of sense.

**Comment by lemire** [comment]
So a pull request is invited!

**Comment by lemire** [comment]
Marking as "help wanted".
