### ISSUE TITLE
Debian packaging for simdjson

### ISSUE THREAD

**Issue by cdluminate** [lemire/simdjson#77]
I've created a Debian package for simdjson: https://salsa.debian.org/debian/simdjson
And it's waiting in Debian's NEW queue: https://ftp-master.debian.org/new/simdjson_0.0~git20190221.3757349-1.html

Sometimes later it will enter Debian unstable. And at that time maybe we can add another "Installation" section to readme?

**Comment by lemire** [comment]
Marked as "help wanted".

**Comment by lemire** [comment]
@cdluminate How is this going?

**Comment by cdluminate** [comment]
https://tracker.debian.org/pkg/simdjson already available for debian unstable. Too late for debian buster. Thanks for reminding me of the remaining issue. Closing now.

**Comment by lemire** [comment]
@cdluminate At some point in the future when we produce a stable version (say much later this summer), how do we push it upstream? Do we ping you?

**Comment by cdluminate** [comment]
debian sid/unstable users can install simdjson with "apt install libsimdjson-dev".

**Comment by cdluminate** [comment]
@lemire feel free to ping me for anything related to Debian.

**Comment by cdluminate** [comment]
I'm watching the releases of this project. No need to manually ping me for new releases.

**Comment by lemire** [comment]
That's great.

**Comment by lemire** [comment]
@cdluminate We have released a new version (0.3). It is an important release for us. Please consider updating the debian package if you can.

**Comment by lemire** [comment]
@cdluminate We released simdjson 0.4.0. Please consider updating the package if you can. We recommend setting SIMDJSON_JUST_LIBRARY=ON when building.

**Comment by cdluminate** [comment]
@lemire Got it. The thing is, 0.3.1 is still stuck at Debian's NEW queue (where packages has to be manually reviewed by the corresponding team). I'll upload 0.4.0 once it has been unblocked.

> @cdluminate We released simdjson 0.4.0. Please consider updating the package if you can. We recommend setting SIMDJSON_JUST_LIBRARY=ON when building.

https://ftp-master.debian.org/new/simdjson_0.3.1-1.html

**Comment by cdluminate** [comment]
FYI: finally simdjson 0.5.0 passed our NEW queue and entered the archive.
https://tracker.debian.org/pkg/simdjson
https://buildd.debian.org/status/package.php?p=simdjson

**Comment by lemire** [comment]
Great news. 0.5 was a very good release, so this makes me happy.

**Comment by cdluminate** [comment]
simdjson 0.6.1 has been uploaded to debian's stable-backports channel. It means debian stable users and debian testing/unstable users are all able to install the library with `apt install libsimdjson-dev`.

**Comment by cdluminate** [comment]
BTW, simdjson 0.6.1 debian package is built for a bunch of architectures: https://buildd.debian.org/status/package.php?p=simdjson&suite=sid

**Comment by lemire** [comment]
Fantastic. Just in time for us to release 0.7!

(I am not joking. I am planning to release 0.7 today.)
