### ISSUE TITLE
Please include https://github.com/mleise/fast

### ISSUE THREAD

**Issue by andre2007** [lemire/simdjson#83]
Some time ago https://github.com/mleise/fast claimed to be the fastest json parser. It would be nice to have it included in the benchmark.

**Comment by lemire** [comment]
It appears to be written in D. From the paper (https://arxiv.org/pdf/1902.08318.pdf):

> For methodological simplicity, we also do not consider parsers written in Java or other languages.

We certainly encourage further benchmarking, but I don't think we will add D as a dependency on this project, here.

**Comment by andre2007** [comment]
Yes it is written in D and it it's statement was, that it is the fastest json parser available. Therefore comparing your implementation  against this parser makes sense.

Also the fastest file system is written in D.

**Comment by plokhotnyuk** [comment]
[That JSON test](https://github.com/kostya/benchmarks#json) is mostly about parsing of float point numbers and it do not check results of parsing precisely. So some authors cheats by using loosing routines: https://github.com/kostya/benchmarks/blob/master/json/json-scala/src/main/scala/JsonTest.scala#L21

**Comment by andre2007** [comment]
@mleise just for your info, I tried to get your library also included into the benchmark. 
Maybe you are interested in comparing how your library is compared to this one?

**Comment by mleise** [comment]
@andre2007 I'll certainly take a look next week. I didn't put a date of expiry on my claims.

**Comment by kostya** [comment]
i added test here https://github.com/kostya/benchmarks#json, d still 30% faster
