### ISSUE TITLE
Are there plan to provide java version simdjon

### ISSUE THREAD

**Issue by bithw1** [lemire/simdjson#93]
Hi,

Would ask to know whether there is a plan to provide a java version simdjon library.

**Comment by lemire** [comment]
There is a C# version https://github.com/EgorBo/SimdJsonSharp

I don’t think anyone is investigating a Java version. 

I think that if we have Panama then it becomes easier... https://openjdk.java.net/projects/panama/

**Comment by bithw1** [comment]
Sure, thanks @lemire for the information

**Comment by lanrobin** [comment]
Would some one is interesting wrapper it through JNI for java user?

**Comment by lemire** [comment]
@lanrobin I think that it would be great. We have Python, JavaScript, C#, Rust(started). I am sure a Java wrapper would generate a lot of interest.
